<?php
    // Communities XML fields
    add_action('init', 'createXmlFields' );

    function createXmlFields()
    {
	    if( function_exists('acf_add_local_field_group') ):

		    acf_add_local_field_group(array(
			    'key' => 'group_626bec776c832',
			    'title' => 'Community Feed',
			    'fields' => array(
				    array(
					    'key' => 'field_626bec8427b6e',
					    'label' => 'General Information',
					    'name' => '',
					    'type' => 'tab',
					    'instructions' => '',
					    'required' => 0,
					    'conditional_logic' => 0,
					    'wrapper' => array(
						    'width' => '',
						    'class' => '',
						    'id' => '',
					    ),
					    'placement' => 'left',
					    'endpoint' => 0,
					    'no_preference' => 1,
					    'acfe_field_group_condition' => 0,
				    ),
				    array(
					    'key' => 'field_626bee9492d6d',
					    'label' => 'Welcome',
					    'name' => '',
					    'type' => 'message',
					    'instructions' => '',
					    'required' => 0,
					    'conditional_logic' => 0,
					    'wrapper' => array(
						    'width' => '',
						    'class' => '',
						    'id' => '',
					    ),
					    'message' => 'The feed format presented below will allow your organization to share new construction listings with
Zillow.',
					    'new_lines' => 'wpautop',
					    'esc_html' => 0,
					    'acfe_field_group_condition' => 0,
				    ),
				    array(
					    'key' => 'field_62cec9901a810',
					    'label' => 'Community Logo',
					    'name' => 'community_logo',
					    'type' => 'image',
					    'instructions' => '',
					    'required' => 0,
					    'conditional_logic' => 0,
					    'wrapper' => array(
						    'width' => '',
						    'class' => '',
						    'id' => '',
					    ),
					    'uploader' => '',
					    'acfe_thumbnail' => 0,
					    'return_format' => 'array',
					    'preview_size' => 'medium',
					    'min_width' => '',
					    'min_height' => '',
					    'min_size' => '',
					    'max_width' => '',
					    'max_height' => '',
					    'max_size' => '',
					    'mime_types' => '',
					    'acfe_field_group_condition' => 0,
					    'library' => 'all',
				    ),
				    array(
					    'key' => 'field_626ffca93b2dc',
					    'label' => '(Column 6/12)',
					    'name' => '',
					    'type' => 'acfe_column',
					    'instructions' => '',
					    'required' => 0,
					    'conditional_logic' => 0,
					    'wrapper' => array(
						    'width' => '',
						    'class' => '',
						    'id' => '',
					    ),
					    'columns' => '6/12',
					    'endpoint' => 0,
					    'border' => '',
					    'acfe_field_group_condition' => 0,
					    'border_endpoint' => array(
						    0 => 'endpoint',
					    ),
				    ),
				    array(
					    'key' => 'field_626bed2792d6c',
					    'label' => 'Listing Status',
					    'name' => 'communty_listing_status',
					    'type' => 'true_false',
					    'instructions' => 'Add this community listing to the Feed',
					    'required' => 0,
					    'conditional_logic' => 0,
					    'wrapper' => array(
						    'width' => '',
						    'class' => '',
						    'id' => '',
					    ),
					    'message' => '',
					    'default_value' => 1,
					    'ui' => 1,
					    'ui_on_text' => 'YES',
					    'ui_off_text' => 'NO',
					    'acfe_field_group_condition' => 0,
				    ),
				    array(
					    'key' => 'field_626ffcf13b2e0',
					    'label' => '(Column 6/12)',
					    'name' => '',
					    'type' => 'acfe_column',
					    'instructions' => '',
					    'required' => 0,
					    'conditional_logic' => 0,
					    'wrapper' => array(
						    'width' => '',
						    'class' => '',
						    'id' => '',
					    ),
					    'columns' => '6/12',
					    'endpoint' => 0,
					    'border' => '',
					    'acfe_field_group_condition' => 0,
					    'border_endpoint' => array(
						    0 => 'endpoint',
					    ),
				    ),
				    array(
					    'key' => 'field_626c009a0a29a',
					    'label' => 'Website',
					    'name' => 'sub_website',
					    'type' => 'url',
					    'instructions' => '',
					    'required' => 0,
					    'conditional_logic' => 0,
					    'wrapper' => array(
						    'width' => '',
						    'class' => '',
						    'id' => '',
					    ),
					    'default_value' => '',
					    'placeholder' => 'Website Url',
					    'acfe_field_group_condition' => 0,
				    ),
				    array(
					    'key' => 'field_626ffcc83b2de',
					    'label' => '(Column Endpoint)',
					    'name' => '',
					    'type' => 'acfe_column',
					    'instructions' => '',
					    'required' => 0,
					    'conditional_logic' => 0,
					    'wrapper' => array(
						    'width' => '',
						    'class' => '',
						    'id' => '',
					    ),
					    'endpoint' => 1,
					    'acfe_field_group_condition' => 0,
					    'columns' => '6/12',
					    'border' => '',
					    'border_endpoint' => array(
						    0 => 'endpoint',
					    ),
				    ),
				    array(
					    'key' => 'field_626ffcea3b2df',
					    'label' => '(Column 6/12)',
					    'name' => '',
					    'type' => 'acfe_column',
					    'instructions' => '',
					    'required' => 0,
					    'conditional_logic' => 0,
					    'wrapper' => array(
						    'width' => '',
						    'class' => '',
						    'id' => '',
					    ),
					    'columns' => '6/12',
					    'endpoint' => 0,
					    'border' => '',
					    'acfe_field_group_condition' => 0,
					    'border_endpoint' => array(
						    0 => 'endpoint',
					    ),
				    ),
				    array(
					    'key' => 'field_626ffc08b1717',
					    'label' => 'Lot Number',
					    'name' => 'comm_lotnumber',
					    'type' => 'text',
					    'instructions' => '',
					    'required' => 0,
					    'conditional_logic' => 0,
					    'wrapper' => array(
						    'width' => '',
						    'class' => '',
						    'id' => '',
					    ),
					    'default_value' => '',
					    'placeholder' => 'Lot Number',
					    'prepend' => '',
					    'append' => '',
					    'maxlength' => 30,
					    'acfe_field_group_condition' => 0,
				    ),
				    array(
					    'key' => 'field_6274113fed8c2',
					    'label' => '(Column 6/12)',
					    'name' => '',
					    'type' => 'acfe_column',
					    'instructions' => '',
					    'required' => 0,
					    'conditional_logic' => 0,
					    'wrapper' => array(
						    'width' => '',
						    'class' => '',
						    'id' => '',
					    ),
					    'columns' => '6/12',
					    'endpoint' => 0,
					    'border' => '',
					    'acfe_field_group_condition' => 0,
					    'border_endpoint' => array(
						    0 => 'endpoint',
					    ),
				    ),
				    array(
					    'key' => 'field_626ffc48b1718',
					    'label' => 'Lot Name',
					    'name' => 'lot_name',
					    'type' => 'text',
					    'instructions' => '',
					    'required' => 0,
					    'conditional_logic' => 0,
					    'wrapper' => array(
						    'width' => '',
						    'class' => '',
						    'id' => '',
					    ),
					    'default_value' => '',
					    'placeholder' => 'Lot Name',
					    'prepend' => '',
					    'append' => '',
					    'maxlength' => 30,
					    'acfe_field_group_condition' => 0,
				    ),
				    array(
					    'key' => 'field_62741148ed8c3',
					    'label' => '(Column Endpoint)',
					    'name' => '',
					    'type' => 'acfe_column',
					    'instructions' => '',
					    'required' => 0,
					    'conditional_logic' => 0,
					    'wrapper' => array(
						    'width' => '',
						    'class' => '',
						    'id' => '',
					    ),
					    'endpoint' => 1,
					    'border_endpoint' => array(
						    0 => 'endpoint',
					    ),
					    'acfe_field_group_condition' => 0,
					    'columns' => '6/12',
					    'border' => '',
				    ),
				    array(
					    'key' => 'field_626bffe83e31f',
					    'label' => 'Sub Description',
					    'name' => 'sub_description',
					    'type' => 'textarea',
					    'instructions' => '',
					    'required' => 0,
					    'conditional_logic' => 0,
					    'wrapper' => array(
						    'width' => '',
						    'class' => '',
						    'id' => '',
					    ),
					    'default_value' => '',
					    'placeholder' => 'A description of the subdivision.',
					    'maxlength' => 2000,
					    'rows' => 4,
					    'new_lines' => '',
					    'acfe_textarea_code' => 0,
					    'acfe_field_group_condition' => 0,
				    ),
				    array(
					    'key' => 'field_626ff8c8ecef4',
					    'label' => 'Services',
					    'name' => '',
					    'type' => 'tab',
					    'instructions' => '',
					    'required' => 0,
					    'conditional_logic' => 0,
					    'wrapper' => array(
						    'width' => '',
						    'class' => '',
						    'id' => '',
					    ),
					    'placement' => 'left',
					    'endpoint' => 0,
					    'no_preference' => 0,
					    'acfe_field_group_condition' => 0,
				    ),
				    array(
					    'key' => 'field_626bfce87c4d3',
					    'label' => 'Services',
					    'name' => 'services',
					    'type' => 'repeater',
					    'instructions' => '',
					    'required' => 0,
					    'conditional_logic' => 0,
					    'wrapper' => array(
						    'width' => '',
						    'class' => '',
						    'id' => '',
					    ),
					    'acfe_repeater_stylised_button' => 1,
					    'collapsed' => 'field_626ff9a002138',
					    'min' => 0,
					    'max' => 0,
					    'layout' => 'block',
					    'button_label' => 'Add Service',
					    'acfe_field_group_condition' => 0,
					    'sub_fields' => array(
						    array(
							    'key' => 'field_626ff9a002138',
							    'label' => 'Service Type',
							    'name' => 'service_type',
							    'type' => 'select',
							    'instructions' => '',
							    'required' => 0,
							    'conditional_logic' => 0,
							    'wrapper' => array(
								    'width' => '',
								    'class' => '',
								    'id' => '',
							    ),
							    'choices' => array(
								    'HOA' => 'HOA',
								    'GroundsCare' => 'Grounds Care',
								    'Security' => 'Security',
								    'Maintenance' => 'Maintenance',
								    'MedicalCare' => 'Medical Care',
								    'Shopping' => 'Shopping',
							    ),
							    'default_value' => false,
							    'allow_null' => 0,
							    'multiple' => 0,
							    'ui' => 1,
							    'ajax' => 1,
							    'return_format' => 'array',
							    'allow_custom' => 0,
							    'search_placeholder' => '',
							    'prepend' => '',
							    'append' => '',
							    'acfe_field_group_condition' => 0,
							    'placeholder' => '',
						    ),
						    array(
							    'key' => 'field_626ffa0802139',
							    'label' => 'Service Name',
							    'name' => 'service_name',
							    'type' => 'text',
							    'instructions' => 'The name of the service. Required if there is a service element.',
							    'required' => 0,
							    'conditional_logic' => array(
								    array(
									    array(
										    'field' => 'field_626ff9a002138',
										    'operator' => '!=empty',
									    ),
								    ),
							    ),
							    'wrapper' => array(
								    'width' => '',
								    'class' => '',
								    'id' => '',
							    ),
							    'default_value' => '',
							    'placeholder' => 'Service Name',
							    'prepend' => '',
							    'append' => '',
							    'maxlength' => '',
							    'acfe_field_group_condition' => 0,
						    ),
						    array(
							    'key' => 'field_626ffa4c0213a',
							    'label' => 'Monthly Fee',
							    'name' => 'monthly_fee',
							    'type' => 'number',
							    'instructions' => 'If the service is paid monthly, the monthly cost. If there is a service element, either the monthly or yearly fee information is required.',
							    'required' => 0,
							    'conditional_logic' => array(
								    array(
									    array(
										    'field' => 'field_626ff9a002138',
										    'operator' => '!=empty',
									    ),
								    ),
							    ),
							    'wrapper' => array(
								    'width' => '',
								    'class' => '',
								    'id' => '',
							    ),
							    'default_value' => '',
							    'placeholder' => 'Monthly Fee',
							    'prepend' => '',
							    'append' => '',
							    'min' => '',
							    'max' => '',
							    'step' => '',
							    'acfe_field_group_condition' => 0,
						    ),
						    array(
							    'key' => 'field_626ffac10213b',
							    'label' => 'Yearly Fee',
							    'name' => 'yearly_fee',
							    'type' => 'number',
							    'instructions' => '',
							    'required' => 0,
							    'conditional_logic' => array(
								    array(
									    array(
										    'field' => 'field_626ff9a002138',
										    'operator' => '!=empty',
									    ),
								    ),
							    ),
							    'wrapper' => array(
								    'width' => '',
								    'class' => '',
								    'id' => '',
							    ),
							    'default_value' => '',
							    'placeholder' => 'Yearly Fee',
							    'prepend' => '',
							    'append' => '',
							    'min' => '',
							    'max' => '',
							    'step' => '',
							    'acfe_field_group_condition' => 0,
						    ),
					    ),
				    ),
				    array(
					    'key' => 'field_626c019c5c99c',
					    'label' => 'Amenities',
					    'name' => '',
					    'type' => 'tab',
					    'instructions' => '',
					    'required' => 0,
					    'conditional_logic' => 0,
					    'wrapper' => array(
						    'width' => '',
						    'class' => '',
						    'id' => '',
					    ),
					    'placement' => 'left',
					    'endpoint' => 0,
					    'no_preference' => 0,
					    'acfe_field_group_condition' => 0,
				    ),
				    array(
					    'key' => 'field_626c01305c99b',
					    'label' => 'Open Amenties',
					    'name' => 'open_amenties',
					    'type' => 'select',
					    'instructions' => '',
					    'required' => 0,
					    'conditional_logic' => 0,
					    'wrapper' => array(
						    'width' => '',
						    'class' => '',
						    'id' => '',
					    ),
					    'choices' => array(
						    'HealthAndFitness' => 'Health And Fitness',
						    'CommunityServices' => 'Community Services',
						    'SocialActivities' => 'Social Activities',
						    'Education' => 'Education',
						    'LocalAreaAmenities' => 'Local Area Amenities',
						    'Custom' => 'Custom',
					    ),
					    'default_value' => array(
					    ),
					    'allow_null' => 0,
					    'multiple' => 1,
					    'min' => '',
					    'max' => '',
					    'ui' => 1,
					    'ajax' => 1,
					    'return_format' => 'array',
					    'allow_custom' => 0,
					    'placeholder' => 'Select',
					    'prepend' => '',
					    'append' => '',
					    'acfe_field_group_condition' => 0,
				    ),
				    array(
					    'key' => 'field_626bfa877c4d1',
					    'label' => 'SubAmenity',
					    'name' => 'sub_amenity',
					    'type' => 'select',
					    'instructions' => 'Indicate whether an amenity exists. This element can be used multiple times, once for each amenity.',
					    'required' => 0,
					    'conditional_logic' => 0,
					    'wrapper' => array(
						    'width' => '',
						    'class' => '',
						    'id' => '',
					    ),
					    'choices' => array(
						    'Basketball' => 'Basketball',
						    'Baseball' => 'Baseball',
						    'Volleyball' => 'Volleyball',
						    'Soccer' => 'Soccer',
						    'Tennis' => 'Tennis',
						    'GolfCourse' => 'Golf Course',
						    'Playground' => 'Playground',
						    'Pool' => 'Pool',
						    'Views' => 'Views',
						    'Lake' => 'Lake',
						    'Pond' => 'Pond',
						    'Beach' => 'Beach',
						    'MarinaWaterfrontLots' => 'Marina Waterfront Lots',
						    'Park' => 'Park',
						    'Trails' => 'Trails',
						    'Greenbelt' => 'Greenbelt',
						    'Clubhouse' => 'Clubhouse',
						    'CommunityCenter' => 'Community Center',
					    ),
					    'default_value' => array(
					    ),
					    'allow_null' => 0,
					    'multiple' => 1,
					    'min' => '',
					    'max' => '',
					    'ui' => 1,
					    'ajax' => 1,
					    'return_format' => 'array',
					    'allow_custom' => 1,
					    'placeholder' => 'Select',
					    'prepend' => '',
					    'append' => '',
					    'acfe_field_group_condition' => 0,
				    ),
				    array(
					    'key' => 'field_626c0223d8d46',
					    'label' => 'Promotion',
					    'name' => '',
					    'type' => 'tab',
					    'instructions' => '',
					    'required' => 0,
					    'conditional_logic' => 0,
					    'wrapper' => array(
						    'width' => '',
						    'class' => '',
						    'id' => '',
					    ),
					    'placement' => 'left',
					    'endpoint' => 0,
					    'no_preference' => 0,
					    'acfe_field_group_condition' => 0,
				    ),
				    array(
					    'key' => 'field_626c023bd8d47',
					    'label' => 'Promo Type',
					    'name' => 'promo_type',
					    'type' => 'select',
					    'instructions' => '',
					    'required' => 0,
					    'conditional_logic' => 0,
					    'wrapper' => array(
						    'width' => '',
						    'class' => '',
						    'id' => '',
					    ),
					    'choices' => array(
						    'Consumer' => 'Consumer',
						    'Agent' => 'Agent',
					    ),
					    'default_value' => false,
					    'allow_null' => 0,
					    'multiple' => 0,
					    'max' => '',
					    'ui' => 1,
					    'ajax' => 1,
					    'return_format' => 'array',
					    'allow_custom' => 0,
					    'search_placeholder' => 'Select',
					    'prepend' => '',
					    'append' => '',
					    'acfe_field_group_condition' => 0,
					    'placeholder' => '',
				    ),
				    array(
					    'key' => 'field_626c0276d8d48',
					    'label' => 'Promo Headline',
					    'name' => 'promo_headline',
					    'type' => 'text',
					    'instructions' => '',
					    'required' => 0,
					    'conditional_logic' => array(
						    array(
							    array(
								    'field' => 'field_626c023bd8d47',
								    'operator' => '==',
								    'value' => 'Consumer',
							    ),
						    ),
					    ),
					    'wrapper' => array(
						    'width' => '',
						    'class' => '',
						    'id' => '',
					    ),
					    'default_value' => '',
					    'placeholder' => 'Promo Headline',
					    'prepend' => '',
					    'append' => '',
					    'maxlength' => '',
					    'acfe_field_group_condition' => 0,
				    ),
				    array(
					    'key' => 'field_626c02a1d8d49',
					    'label' => 'Promo Description',
					    'name' => 'promo_description',
					    'type' => 'text',
					    'instructions' => '',
					    'required' => 0,
					    'conditional_logic' => array(
						    array(
							    array(
								    'field' => 'field_626c023bd8d47',
								    'operator' => '==',
								    'value' => 'Consumer',
							    ),
						    ),
					    ),
					    'wrapper' => array(
						    'width' => '',
						    'class' => '',
						    'id' => '',
					    ),
					    'default_value' => '',
					    'placeholder' => 'Promo Description',
					    'prepend' => '',
					    'append' => '',
					    'maxlength' => '',
					    'acfe_field_group_condition' => 0,
				    ),
				    array(
					    'key' => 'field_626c02c8d8d4a',
					    'label' => 'Start Date',
					    'name' => 'start_date',
					    'type' => 'date_picker',
					    'instructions' => '',
					    'required' => 0,
					    'conditional_logic' => array(
						    array(
							    array(
								    'field' => 'field_626c023bd8d47',
								    'operator' => '==',
								    'value' => 'Consumer',
							    ),
						    ),
					    ),
					    'wrapper' => array(
						    'width' => '',
						    'class' => '',
						    'id' => '',
					    ),
					    'display_format' => 'Y-m-d',
					    'return_format' => 'Y-m-d',
					    'first_day' => 1,
					    'placeholder' => '',
					    'min_date' => '',
					    'max_date' => '',
					    'no_weekends' => 0,
					    'acfe_field_group_condition' => 0,
				    ),
				    array(
					    'key' => 'field_626c0311d8d4b',
					    'label' => 'End Date',
					    'name' => 'end_date',
					    'type' => 'date_picker',
					    'instructions' => '',
					    'required' => 0,
					    'conditional_logic' => array(
						    array(
							    array(
								    'field' => 'field_626c023bd8d47',
								    'operator' => '==',
								    'value' => 'Consumer',
							    ),
						    ),
					    ),
					    'wrapper' => array(
						    'width' => '',
						    'class' => '',
						    'id' => '',
					    ),
					    'display_format' => 'yyy-mm-dd',
					    'return_format' => 'Y-m-d',
					    'first_day' => 1,
					    'placeholder' => '',
					    'min_date' => '',
					    'max_date' => '',
					    'no_weekends' => 0,
					    'acfe_field_group_condition' => 0,
				    ),
				    array(
					    'key' => 'field_626ffdf5e2ca3',
					    'label' => 'Hours of Operations',
					    'name' => '',
					    'type' => 'tab',
					    'instructions' => '',
					    'required' => 0,
					    'conditional_logic' => 0,
					    'wrapper' => array(
						    'width' => '',
						    'class' => '',
						    'id' => '',
					    ),
					    'placement' => 'left',
					    'endpoint' => 0,
					    'no_preference' => 0,
					    'acfe_field_group_condition' => 0,
				    ),
				    array(
					    'key' => 'field_62700042e2ca9',
					    'label' => 'By Appointment',
					    'name' => 'by_appointment',
					    'type' => 'true_false',
					    'instructions' => 'Is the office open by appointment?',
					    'required' => 0,
					    'conditional_logic' => 0,
					    'wrapper' => array(
						    'width' => '',
						    'class' => '',
						    'id' => '',
					    ),
					    'message' => '',
					    'default_value' => 0,
					    'ui' => 1,
					    'ui_on_text' => 'Yes',
					    'ui_off_text' => 'No',
					    'acfe_field_group_condition' => 0,
				    ),
				    array(
					    'key' => 'field_626ffe5be2ca4',
					    'label' => 'Hours Details',
					    'name' => 'hours_details',
					    'type' => 'repeater',
					    'instructions' => '',
					    'required' => 0,
					    'conditional_logic' => 0,
					    'wrapper' => array(
						    'width' => '',
						    'class' => '',
						    'id' => '',
					    ),
					    'acfe_repeater_stylised_button' => 1,
					    'collapsed' => 'field_626ffe78e2ca5',
					    'min' => 0,
					    'max' => 7,
					    'layout' => 'block',
					    'button_label' => '',
					    'acfe_field_group_condition' => 0,
					    'sub_fields' => array(
						    array(
							    'key' => 'field_626ffe78e2ca5',
							    'label' => 'Day of Week',
							    'name' => 'day_of_week',
							    'type' => 'select',
							    'instructions' => '',
							    'required' => 0,
							    'conditional_logic' => 0,
							    'wrapper' => array(
								    'width' => '',
								    'class' => '',
								    'id' => '',
							    ),
							    'choices' => array(
								    'Monday' => 'Monday',
								    'Tuesday' => 'Tuesday',
								    'Wednesday' => 'Wednesday',
								    'Thursday' => 'Thursday',
								    'Friday' => 'Friday',
								    'Saturday' => 'Saturday',
								    'Sunday' => 'Sunday',
							    ),
							    'default_value' => false,
							    'allow_null' => 0,
							    'multiple' => 0,
							    'max' => '',
							    'ui' => 1,
							    'ajax' => 1,
							    'return_format' => 'array',
							    'allow_custom' => 0,
							    'search_placeholder' => 'Day of Week',
							    'prepend' => '',
							    'append' => '',
							    'acfe_field_group_condition' => 0,
							    'placeholder' => '',
						    ),
						    array(
							    'key' => 'field_626fff10e2ca6',
							    'label' => 'Start Time',
							    'name' => 'start_time',
							    'type' => 'time_picker',
							    'instructions' => '',
							    'required' => 0,
							    'conditional_logic' => array(
								    array(
									    array(
										    'field' => 'field_626ffe78e2ca5',
										    'operator' => '!=empty',
									    ),
								    ),
							    ),
							    'wrapper' => array(
								    'width' => '',
								    'class' => '',
								    'id' => '',
							    ),
							    'display_format' => 'hh:mm',
							    'return_format' => 'hh:mm',
							    'placeholder' => '',
							    'min_time' => '',
							    'max_time' => '',
							    'min_hour' => '',
							    'max_hour' => '',
							    'min_min' => '',
							    'max_min' => '',
							    'min_sec' => '',
							    'max_sec' => '',
							    'acfe_field_group_condition' => 0,
						    ),
						    array(
							    'key' => 'field_626fff8ee2ca7',
							    'label' => 'End Time',
							    'name' => 'end_time',
							    'type' => 'time_picker',
							    'instructions' => '',
							    'required' => 0,
							    'conditional_logic' => array(
								    array(
									    array(
										    'field' => 'field_626ffe78e2ca5',
										    'operator' => '!=empty',
									    ),
								    ),
							    ),
							    'wrapper' => array(
								    'width' => '',
								    'class' => '',
								    'id' => '',
							    ),
							    'display_format' => 'hh:mm',
							    'return_format' => 'hh:mm',
							    'placeholder' => '',
							    'min_time' => '',
							    'max_time' => '',
							    'min_hour' => '',
							    'max_hour' => '',
							    'min_min' => '',
							    'max_min' => '',
							    'min_sec' => '',
							    'max_sec' => '',
							    'acfe_field_group_condition' => 0,
						    ),
					    ),
				    ),
				    array(
					    'key' => 'field_62cec8a246120',
					    'label' => 'MLS Listing Connect',
					    'name' => '',
					    'type' => 'tab',
					    'instructions' => '',
					    'required' => 0,
					    'conditional_logic' => 0,
					    'wrapper' => array(
						    'width' => '',
						    'class' => '',
						    'id' => '',
					    ),
					    'placement' => 'left',
					    'endpoint' => 0,
					    'no_preference' => 0,
					    'acfe_field_group_condition' => 0,
				    ),
				    array(
					    'key' => 'field_62cec8cc46121',
					    'label' => 'MLS Identifier',
					    'name' => 'mls_identifier',
					    'type' => 'text',
					    'instructions' => '',
					    'required' => 0,
					    'conditional_logic' => 0,
					    'wrapper' => array(
						    'width' => '',
						    'class' => '',
						    'id' => '',
					    ),
					    'default_value' => '',
					    'placeholder' => '',
					    'prepend' => '',
					    'append' => '',
					    'maxlength' => '',
					    'acfe_field_group_condition' => 0,
				    ),
				    array(
					    'key' => 'field_62cec8ec46122',
					    'label' => 'MLS Listing IDs',
					    'name' => 'mls_listing_ids',
					    'type' => 'repeater',
					    'instructions' => '',
					    'required' => 0,
					    'conditional_logic' => 0,
					    'wrapper' => array(
						    'width' => '',
						    'class' => '',
						    'id' => '',
					    ),
					    'acfe_repeater_stylised_button' => 1,
					    'collapsed' => '',
					    'min' => 0,
					    'max' => 0,
					    'layout' => 'table',
					    'button_label' => 'Add Listing ID',
					    'acfe_field_group_condition' => 0,
					    'sub_fields' => array(
						    array(
							    'key' => 'field_62cec90846123',
							    'label' => 'Listing ID',
							    'name' => 'listing_id',
							    'type' => 'text',
							    'instructions' => '',
							    'required' => 0,
							    'conditional_logic' => 0,
							    'wrapper' => array(
								    'width' => '',
								    'class' => '',
								    'id' => '',
							    ),
							    'default_value' => '',
							    'placeholder' => '',
							    'prepend' => '',
							    'append' => '',
							    'maxlength' => '',
							    'acfe_field_group_condition' => 0,
						    ),
					    ),
				    ),
			    ),
			    'location' => array(
				    array(
					    array(
						    'param' => 'post_type',
						    'operator' => '==',
						    'value' => 'communities',
					    ),
				    ),
			    ),
			    'menu_order' => 1,
			    'position' => 'acf_after_title',
			    'style' => 'default',
			    'label_placement' => 'top',
			    'instruction_placement' => 'tooltip',
			    'hide_on_screen' => '',
			    'active' => true,
			    'description' => '',
			    'acfe_autosync' => '',
			    'acfe_form' => 0,
			    'acfe_display_title' => '',
			    'acfe_meta' => '',
			    'acfe_note' => '',
		    ));

	    endif;
    }
