<?php

    add_action('init', 'enablePlanFiedls');

    function enablePlanFiedls()
    {
        if( function_exists('acf_add_local_field_group') ):

            acf_add_local_field_group(array(
                'key' => 'group_62700194e0d14',
                'title' => 'Floorplans Feed',
                'fields' => array(
                    array(
                        'key' => 'field_627001d2e7747',
                        'label' => 'General Information',
                        'name' => '',
                        'type' => 'tab',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'placement' => 'left',
                        'endpoint' => 1,
                        'no_preference' => 0,
                        'acfe_field_group_condition' => 0,
                    ),
                    array(
                        'key' => 'field_6272d530b0f30',
                        'label' => 'Listing Status',
                        'name' => 'plan_listing_status',
                        'type' => 'true_false',
                        'instructions' => 'Toggle to yes to include this floorplan in the feed',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'message' => '',
                        'default_value' => 0,
                        'ui' => 1,
                        'ui_on_text' => 'Yes',
                        'ui_off_text' => 'No',
                        'acfe_field_group_condition' => 0,
                    ),
                    array(
                        'key' => 'field_627005740e504',
                        'label' => 'Plan Website',
                        'name' => 'plan_website',
                        'type' => 'url',
                        'instructions' => 'Link to a website with more information about the plan.',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'default_value' => '',
                        'placeholder' => 'Plan Website',
                        'acfe_field_group_condition' => 0,
                    ),
                    array(
                        'key' => 'field_627003e4e774a',
                        'label' => '(Column 6/12)',
                        'name' => '',
                        'type' => 'acfe_column',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'columns' => '6/12',
                        'endpoint' => 0,
                        'border' => '',
                        'acfe_field_group_condition' => 0,
                        'border_endpoint' => array(
                            0 => 'endpoint',
                        ),
                    ),
                    array(
                        'key' => 'field_627002e4e7748',
                        'label' => 'Plan Type',
                        'name' => 'plan_type',
                        'type' => 'select',
                        'instructions' => 'Condos and townhomes should use MultiFamily.',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'choices' => array(
                            'SingleFamily' => 'Single Family',
                            'MultiFamily' => 'Multi-Family',
                        ),
                        'default_value' => false,
                        'allow_null' => 0,
                        'multiple' => 0,
                        'ui' => 1,
                        'ajax' => 1,
                        'return_format' => 'array',
                        'allow_custom' => 0,
                        'search_placeholder' => 'Plan Type',
                        'prepend' => '',
                        'append' => '',
                        'acfe_field_group_condition' => 0,
                        'placeholder' => '',
                    ),
                    array(
                        'key' => 'field_62700a73e8349',
                        'label' => '(Column 6/12)',
                        'name' => '',
                        'type' => 'acfe_column',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'columns' => '6/12',
                        'endpoint' => 0,
                        'border' => '',
                        'acfe_field_group_condition' => 0,
                        'border_endpoint' => array(
                            0 => 'endpoint',
                        ),
                    ),
                    array(
                        'key' => 'field_62700345e7749',
                        'label' => 'Plan Type Name',
                        'name' => 'plan_type_name',
                        'type' => 'select',
                        'instructions' => 'The specific type of house for this plan.',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'choices' => array(
                            'SingleFamily' => 'Single Family',
                            'Condominium' => 'Condominium',
                            'Townhome' => 'Townhome',
                            'Townhouse' => 'Townhouse',
                            'CarriageHouse' => 'Carriage House',
                            'GardenHome' => 'Garden Home',
                            'Duplex' => 'Duplex',
                            'Multiplex' => 'Multiplex',
                        ),
                        'default_value' => false,
                        'allow_null' => 0,
                        'multiple' => 0,
                        'max' => '',
                        'ui' => 1,
                        'ajax' => 1,
                        'return_format' => 'array',
                        'allow_custom' => 0,
                        'search_placeholder' => 'Plan Type Name',
                        'prepend' => '',
                        'append' => '',
                        'acfe_field_group_condition' => 0,
                        'placeholder' => '',
                    ),
                    array(
                        'key' => 'field_627003fae774c',
                        'label' => '(Column Endpoint)',
                        'name' => '',
                        'type' => 'acfe_column',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'endpoint' => 1,
                        'acfe_field_group_condition' => 0,
                        'columns' => '6/12',
                        'border' => '',
                        'border_endpoint' => array(
                            0 => 'endpoint',
                        ),
                    ),
                    array(
                        'key' => 'field_627006700e506',
                        'label' => '(Column 4/12)',
                        'name' => '',
                        'type' => 'acfe_column',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'columns' => '4/12',
                        'endpoint' => 0,
                        'border' => '',
                        'acfe_field_group_condition' => 0,
                        'border_endpoint' => array(
                            0 => 'endpoint',
                        ),
                    ),
                    array(
                        'key' => 'field_62700969c387e',
                        'label' => 'Deck',
                        'name' => 'deck',
                        'type' => 'true_false',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'message' => '',
                        'default_value' => 0,
                        'ui' => 1,
                        'ui_on_text' => 'Yes',
                        'ui_off_text' => 'No',
                        'acfe_field_group_condition' => 0,
                    ),
                    array(
                        'key' => 'field_62700a82e834a',
                        'label' => '(Column 4/12)',
                        'name' => '',
                        'type' => 'acfe_column',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'columns' => '4/12',
                        'endpoint' => 0,
                        'border' => '',
                        'acfe_field_group_condition' => 0,
                        'border_endpoint' => array(
                            0 => 'endpoint',
                        ),
                    ),
                    array(
                        'key' => 'field_627006410e505',
                        'label' => 'Attic',
                        'name' => 'attic',
                        'type' => 'true_false',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'message' => '',
                        'default_value' => 0,
                        'ui' => 1,
                        'ui_on_text' => 'Yes',
                        'ui_off_text' => 'No',
                        'acfe_field_group_condition' => 0,
                    ),
                    array(
                        'key' => 'field_62700a88e834b',
                        'label' => '(Column 4/12)',
                        'name' => '',
                        'type' => 'acfe_column',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'columns' => '4/12',
                        'endpoint' => 0,
                        'border' => '',
                        'acfe_field_group_condition' => 0,
                        'border_endpoint' => array(
                            0 => 'endpoint',
                        ),
                    ),
                    array(
                        'key' => 'field_62700a60e8348',
                        'label' => 'Patio',
                        'name' => 'patio',
                        'type' => 'true_false',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'message' => '',
                        'default_value' => 0,
                        'ui' => 1,
                        'ui_on_text' => 'Yes',
                        'ui_off_text' => 'No',
                        'acfe_field_group_condition' => 0,
                    ),
                    array(
                        'key' => 'field_62700a93e834c',
                        'label' => '(Column Endpoint)',
                        'name' => '',
                        'type' => 'acfe_column',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'endpoint' => 1,
                        'border_endpoint' => array(
                            0 => 'endpoint',
                        ),
                        'acfe_field_group_condition' => 0,
                        'columns' => '6/12',
                        'border' => '',
                    ),
                    array(
                        'key' => 'field_6270079e80d75',
                        'label' => 'Exterior Type',
                        'name' => 'exterior_type',
                        'type' => 'select',
                        'instructions' => 'Multiples allowed.',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'choices' => array(
                            'Brick' => 'Brick',
                            'CementConcrete' => 'Cement Concrete',
                            'Composition' => 'Composition',
                            'Metal' => 'Metal',
                            'Shingle' => 'Shingle',
                            'Stone' => 'Stone',
                            'Stucco' => 'Stucco',
                            'Vinyl' => 'Vinyl',
                            'Wood' => 'Wood',
                            'WoodProducts' => 'Wood Products',
                            'Other' => 'Other',
                        ),
                        'default_value' => array(
                        ),
                        'allow_null' => 0,
                        'multiple' => 1,
                        'min' => '',
                        'max' => '',
                        'ui' => 1,
                        'ajax' => 1,
                        'return_format' => 'array',
                        'allow_custom' => 0,
                        'placeholder' => 'Exterior Type',
                        'prepend' => '',
                        'append' => '',
                        'acfe_field_group_condition' => 0,
                    ),
                    array(
                        'key' => 'field_6270068e0e509',
                        'label' => 'Architecture Style',
                        'name' => 'architecture_style',
                        'type' => 'select',
                        'instructions' => 'Select Architecture Style',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'choices' => array(
                            'Bungalow' => 'Bungalow',
                            'CapeCod' => 'CapeCod',
                            'Colonial' => 'Colonial',
                            'Contemporary' => 'Contemporary',
                            'Craftsman' => 'Craftsman',
                            'French' => 'French',
                            'Georgian' => 'Georgian',
                            'Loft' => 'Loft',
                            'Modern' => 'Modern',
                            'Queen AnneVictorian' => 'Queen AnneVictorian',
                            'RanchRambler' => 'Ranch Rambler',
                            'SantaFePuebloStyle' => 'Santa FePueblo Style',
                            'Spanish' => 'Spanish',
                            'Split-level' => 'Split-level',
                            'Tudor' => 'Tudor',
                            'Other' => 'Other',
                        ),
                        'default_value' => false,
                        'allow_null' => 0,
                        'multiple' => 0,
                        'max' => '',
                        'ui' => 1,
                        'ajax' => 1,
                        'return_format' => 'array',
                        'allow_custom' => 0,
                        'search_placeholder' => 'Architecture Style',
                        'prepend' => '',
                        'append' => '',
                        'acfe_field_group_condition' => 0,
                        'placeholder' => '',
                    ),
                    array(
                        'key' => 'field_627008f8c387d',
                        'label' => 'Cooling System',
                        'name' => 'cooling_system',
                        'type' => 'select',
                        'instructions' => 'Multiples allowed.',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'choices' => array(
                            'None' => 'None',
                            'Central' => 'Central',
                            'Evaporative' => 'Evaporative',
                            'Geothermal' => 'Geothermal',
                            'Wall' => 'Wall',
                            'Solar' => 'Solar',
                            'Other' => 'Other',
                        ),
                        'default_value' => array(
                        ),
                        'allow_null' => 0,
                        'multiple' => 1,
                        'min' => '',
                        'max' => '',
                        'ui' => 1,
                        'ajax' => 0,
                        'return_format' => 'array',
                        'allow_custom' => 0,
                        'placeholder' => 'Cooling System',
                        'prepend' => '',
                        'append' => '',
                        'acfe_field_group_condition' => 0,
                    ),
                    array(
                        'key' => 'field_62700b11f4f18',
                        'label' => 'Heating Fuel',
                        'name' => 'heating_fuel',
                        'type' => 'select',
                        'instructions' => 'Multiples allowed.',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'choices' => array(
                            'None' => 'None',
                            'Coal' => 'Coal',
                            'Electric' => 'Electric',
                            'Gas' => 'Gas',
                            'Oil' => 'Oil',
                            'PropaneButane' => 'Propane Butane',
                            'Solar' => 'Solar',
                            'WoodPellet' => 'Wood Pellet',
                            'Other' => 'Other',
                        ),
                        'default_value' => array(
                        ),
                        'allow_null' => 0,
                        'multiple' => 1,
                        'min' => '',
                        'max' => '',
                        'ui' => 1,
                        'ajax' => 1,
                        'return_format' => 'array',
                        'allow_custom' => 0,
                        'placeholder' => 'Heating Fuel',
                        'prepend' => '',
                        'append' => '',
                        'acfe_field_group_condition' => 0,
                    ),
                    array(
                        'key' => 'field_62700b81f4f19',
                        'label' => 'Heating System',
                        'name' => 'heating_system',
                        'type' => 'select',
                        'instructions' => 'Multiples allowed.',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'choices' => array(
                            'Baseboard' => 'Baseboard',
                            'ForcedAir' => 'Forced Air',
                            'HeatPump' => 'Heat Pump',
                            'Radiant' => 'Radiant',
                            'Stove' => 'Stove',
                            'Wall' => 'Wall',
                            'Other' => 'Other',
                        ),
                        'default_value' => array(
                        ),
                        'allow_null' => 0,
                        'multiple' => 1,
                        'min' => '',
                        'max' => '',
                        'ui' => 1,
                        'ajax' => 1,
                        'return_format' => 'array',
                        'allow_custom' => 0,
                        'placeholder' => '',
                        'prepend' => '',
                        'append' => '',
                        'acfe_field_group_condition' => 0,
                    ),
                    array(
                        'key' => 'field_62700c15f4f1a',
                        'label' => 'Parking Type',
                        'name' => 'parking_type',
                        'type' => 'select',
                        'instructions' => 'Multiples allowed.',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'choices' => array(
                            'Asphalt' => 'Asphalt',
                            'BuiltUp' => 'Built-Up',
                            'Composition' => 'Composition',
                            'Metal' => 'Metal',
                            'ShakeShingle' => 'ShakeS hingle',
                            'Slate' => 'Slate',
                            'Tile' => 'Tile',
                            'Other' => 'Other',
                        ),
                        'default_value' => array(
                        ),
                        'allow_null' => 0,
                        'multiple' => 1,
                        'min' => '',
                        'max' => '',
                        'ui' => 1,
                        'ajax' => 1,
                        'return_format' => 'array',
                        'allow_custom' => 0,
                        'placeholder' => '',
                        'prepend' => '',
                        'append' => '',
                        'acfe_field_group_condition' => 0,
                    ),
                    array(
                        'key' => 'field_62700dc1bbff2',
                        'label' => 'Description',
                        'name' => 'feed_plan_description',
                        'type' => 'textarea',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'default_value' => '',
                        'placeholder' => '',
                        'maxlength' => 2000,
                        'rows' => 4,
                        'new_lines' => '',
                        'acfe_textarea_code' => 0,
                        'acfe_field_group_condition' => 0,
                    ),
                    array(
                        'key' => 'field_62700463000d3',
                        'label' => 'Plan Amenity',
                        'name' => '',
                        'type' => 'tab',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'placement' => 'left',
                        'endpoint' => 0,
                        'no_preference' => 0,
                        'acfe_field_group_condition' => 0,
                    ),
                    array(
                        'key' => 'field_6270047d000d4',
                        'label' => 'Plan Amenity',
                        'name' => '',
                        'type' => 'message',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'message' => 'Indicate whether a type of amenity exists. This element can be used multiple times, once for each Type.',
                        'new_lines' => 'wpautop',
                        'esc_html' => 0,
                        'acfe_field_group_condition' => 0,
                    ),
                    array(
                        'key' => 'field_6270049b000d5',
                        'label' => 'Plan Amenity Type',
                        'name' => 'plan_amenity_type',
                        'type' => 'select',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'choices' => array(
                            'BayWindows' => 'Bay Windows',
                            'BreakfastArea' => 'Breakfast Area',
                            'CoveredPatio' => 'Covered Patio',
                            'Fireplaces' => 'Fireplaces',
                            'GreenConstruction' => 'Green Construction',
                            'MudRoom' => 'Mud Room',
                            'Playroom' => 'Playroom',
                            'VaultedCeilings' => 'Vaulted Ceilings',
                            'WalkInClosets' => 'WalkInClosets',
                        ),
                        'default_value' => array(
                        ),
                        'allow_null' => 0,
                        'multiple' => 1,
                        'min' => '',
                        'max' => '',
                        'ui' => 1,
                        'ajax' => 1,
                        'return_format' => 'array',
                        'allow_custom' => 0,
                        'placeholder' => 'Plan Amenity Type',
                        'prepend' => '',
                        'append' => '',
                        'acfe_field_group_condition' => 0,
                    ),
                ),
                'location' => array(
                    array(
                        array(
                            'param' => 'post_type',
                            'operator' => '==',
                            'value' => 'plans',
                        ),
                    ),
                ),
                'menu_order' => 0,
                'position' => 'normal',
                'style' => 'default',
                'label_placement' => 'top',
                'instruction_placement' => 'label',
                'hide_on_screen' => '',
                'active' => true,
                'description' => '',
                'acfe_autosync' => '',
                'acfe_form' => 0,
                'acfe_display_title' => '',
                'acfe_meta' => '',
                'acfe_note' => '',
            ));
            
            endif;

    }