<?php
    add_action('init', 'createHomesFields');

    function createHomesFields()
    {
	    if( function_exists('acf_add_local_field_group') ):

		    acf_add_local_field_group(array(
			    'key' => 'group_62700f22ce4c5',
			    'title' => 'Available Homes Feed',
			    'fields' => array(
				    array(
					    'key' => 'field_62700f2c32e2a',
					    'label' => 'General Information',
					    'name' => '',
					    'type' => 'tab',
					    'instructions' => '',
					    'required' => 0,
					    'conditional_logic' => 0,
					    'wrapper' => array(
						    'width' => '',
						    'class' => '',
						    'id' => '',
					    ),
					    'placement' => 'left',
					    'endpoint' => 0,
					    'no_preference' => 0,
					    'acfe_field_group_condition' => 0,
				    ),
				    array(
					    'key' => 'field_62ceca168ccdb',
					    'label' => 'MLS Number',
					    'name' => 'mls_number',
					    'type' => 'text',
					    'instructions' => '',
					    'required' => 0,
					    'conditional_logic' => 0,
					    'wrapper' => array(
						    'width' => '',
						    'class' => '',
						    'id' => '',
					    ),
					    'default_value' => '',
					    'placeholder' => '',
					    'prepend' => '',
					    'append' => '',
					    'maxlength' => '',
					    'acfe_field_group_condition' => 0,
				    ),
				    array(
					    'key' => 'field_62700f5432e2b',
					    'label' => 'Parcel Number',
					    'name' => 'parcel_number',
					    'type' => 'text',
					    'instructions' => 'The county-assigned parcel number of the lot for this home.',
					    'required' => 0,
					    'conditional_logic' => 0,
					    'wrapper' => array(
						    'width' => '',
						    'class' => '',
						    'id' => '',
					    ),
					    'default_value' => '',
					    'placeholder' => 'Parcel Number',
					    'prepend' => '',
					    'append' => '',
					    'maxlength' => 32,
					    'acfe_field_group_condition' => 0,
				    ),
				    array(
					    'key' => 'field_627014d4a7283',
					    'label' => 'Year Built',
					    'name' => 'year_built',
					    'type' => 'date_picker',
					    'instructions' => 'The year construction started on the home.',
					    'required' => 0,
					    'conditional_logic' => 0,
					    'wrapper' => array(
						    'width' => '',
						    'class' => '',
						    'id' => '',
					    ),
					    'display_format' => 'Y',
					    'return_format' => 'Y',
					    'first_day' => 1,
					    'placeholder' => '',
					    'min_date' => '',
					    'max_date' => '',
					    'no_weekends' => 0,
					    'acfe_field_group_condition' => 0,
				    ),
				    array(
					    'key' => 'field_62700f8b32e2c',
					    'label' => 'Spec Sale Status',
					    'name' => 'spec_sale_status',
					    'type' => 'select',
					    'instructions' => 'If SpecStatus is not provided, provide this element to indicate if the spec home is under contract or sold.',
					    'required' => 0,
					    'conditional_logic' => 0,
					    'wrapper' => array(
						    'width' => '',
						    'class' => '',
						    'id' => '',
					    ),
					    'choices' => array(
						    'ContractPending' => 'Contract Pending',
						    'Sold' => 'Sold',
					    ),
					    'default_value' => false,
					    'allow_null' => 0,
					    'multiple' => 0,
					    'max' => '',
					    'ui' => 1,
					    'ajax' => 1,
					    'return_format' => 'array',
					    'allow_custom' => 0,
					    'search_placeholder' => 'Spec Sale Status',
					    'prepend' => '',
					    'append' => '',
					    'acfe_field_group_condition' => 0,
					    'placeholder' => '',
				    ),
				    array(
					    'key' => 'field_62700fe932e2d',
					    'label' => 'Spec Lot',
					    'name' => 'spec_lot',
					    'type' => 'text',
					    'instructions' => 'The value provided for <LotNumber> for the lot this spec home is associated with.',
					    'required' => 0,
					    'conditional_logic' => 0,
					    'wrapper' => array(
						    'width' => '',
						    'class' => '',
						    'id' => '',
					    ),
					    'default_value' => '',
					    'placeholder' => 'Spec Lot',
					    'prepend' => '',
					    'append' => '',
					    'maxlength' => 30,
					    'acfe_field_group_condition' => 0,
				    ),
				    array(
					    'key' => 'field_6270102332e2e',
					    'label' => 'Spec Status',
					    'name' => 'spec_status',
					    'type' => 'select',
					    'instructions' => 'The status of this spec home.',
					    'required' => 0,
					    'conditional_logic' => 0,
					    'wrapper' => array(
						    'width' => '',
						    'class' => '',
						    'id' => '',
					    ),
					    'choices' => array(
						    'UnderConstruction' => 'Under Construction',
						    'MoveInReady' => 'Move-In Ready',
						    'Reserved' => 'Reserved',
						    'Sold' => 'Sold',
					    ),
					    'default_value' => false,
					    'allow_null' => 0,
					    'multiple' => 0,
					    'max' => '',
					    'ui' => 1,
					    'ajax' => 1,
					    'return_format' => 'array',
					    'allow_custom' => 0,
					    'search_placeholder' => 'Spec Status',
					    'prepend' => '',
					    'append' => '',
					    'acfe_field_group_condition' => 0,
					    'placeholder' => '',
				    ),
				    array(
					    'key' => 'field_627010d132e2f',
					    'label' => 'Spec Move-In Date',
					    'name' => 'spec_move-in_date',
					    'type' => 'group',
					    'instructions' => 'Expected completion date of the home.',
					    'required' => 0,
					    'conditional_logic' => 0,
					    'wrapper' => array(
						    'width' => '',
						    'class' => '',
						    'id' => '',
					    ),
					    'layout' => 'block',
					    'acfe_seamless_style' => 0,
					    'acfe_group_modal' => 0,
					    'acfe_field_group_condition' => 0,
					    'sub_fields' => array(
						    array(
							    'key' => 'field_627010f632e30',
							    'label' => 'Month',
							    'name' => 'month',
							    'type' => 'date_picker',
							    'instructions' => '',
							    'required' => 0,
							    'conditional_logic' => 0,
							    'wrapper' => array(
								    'width' => '',
								    'class' => '',
								    'id' => '',
							    ),
							    'display_format' => 'd/m/Y',
							    'return_format' => 'd/m/Y',
							    'first_day' => 1,
							    'placeholder' => '',
							    'min_date' => '',
							    'max_date' => '',
							    'no_weekends' => 0,
							    'acfe_field_group_condition' => 0,
						    ),
					    ),
				    ),
				    array(
					    'key' => 'field_62701554e266c',
					    'label' => 'Appliance',
					    'name' => 'appliance',
					    'type' => 'select',
					    'instructions' => 'What appliances are included in the home?
Multiples allowed',
					    'required' => 0,
					    'conditional_logic' => 0,
					    'wrapper' => array(
						    'width' => '',
						    'class' => '',
						    'id' => '',
					    ),
					    'choices' => array(
						    'Dishwasher' => 'Dishwasher',
						    'Dryer' => 'Dryer',
						    'Freezer' => 'Freezer',
						    'GarbageDisposal' => 'Garbage Disposal',
						    'Microwave' => 'Microwave',
						    'RangeOven' => 'Range-Oven',
						    'Refrigerator' => 'Refrigerator',
						    'TrashCompactor' => 'Trash Compactor',
						    'Washer' => 'Washer',
					    ),
					    'default_value' => array(
					    ),
					    'allow_null' => 0,
					    'multiple' => 1,
					    'min' => '',
					    'max' => '',
					    'ui' => 1,
					    'ajax' => 1,
					    'return_format' => 'array',
					    'allow_custom' => 0,
					    'placeholder' => 'Appliance',
					    'prepend' => '',
					    'append' => '',
					    'acfe_field_group_condition' => 0,
				    ),
				    array(
					    'key' => 'field_627015e98802c',
					    'label' => 'Architecture Style',
					    'name' => 'architecture_style',
					    'type' => 'select',
					    'instructions' => '',
					    'required' => 0,
					    'conditional_logic' => 0,
					    'wrapper' => array(
						    'width' => '',
						    'class' => '',
						    'id' => '',
					    ),
					    'choices' => array(
						    'Bungalow' => 'Bungalow',
						    'CapeCod' => 'CapeCod',
						    'Colonial' => 'Colonial',
						    'Contemporary' => 'Contemporary',
						    'Craftsman' => 'Craftsman',
						    'French' => 'French',
						    'Georgian' => 'Georgian',
						    'Loft' => 'Loft',
						    'Modern' => 'Modern',
						    'Queen' => 'Queen',
						    'AnneVictorian' => 'AnneVictorian',
						    'RanchRambler' => 'RanchRambler',
						    'SantaFePuebloStyle' => 'SantaFePuebloStyle',
						    'Spanish' => 'Spanish',
						    'Split-level' => 'Split-level',
						    'Tudor' => 'Tudor',
						    'Other' => 'Other',
					    ),
					    'default_value' => false,
					    'allow_null' => 0,
					    'multiple' => 0,
					    'max' => '',
					    'ui' => 1,
					    'ajax' => 1,
					    'return_format' => 'value',
					    'allow_custom' => 0,
					    'search_placeholder' => 'Architecture Style',
					    'prepend' => '',
					    'append' => '',
					    'acfe_field_group_condition' => 0,
					    'placeholder' => '',
				    ),
				    array(
					    'key' => 'field_627016888802e',
					    'label' => 'Exterior Type',
					    'name' => 'exterior_type',
					    'type' => 'select',
					    'instructions' => 'Multiples allowed.',
					    'required' => 0,
					    'conditional_logic' => 0,
					    'wrapper' => array(
						    'width' => '',
						    'class' => '',
						    'id' => '',
					    ),
					    'choices' => array(
						    'Brick' => 'Brick',
						    'CementConcrete' => 'CementConcrete',
						    'Composition' => 'Composition',
						    'Metal' => 'Metal',
						    'Shingle' => 'Shingle',
						    'Stone' => 'Stone',
						    'Stucco' => 'Stucco',
						    'Vinyl' => 'Vinyl',
						    'Wood' => 'Wood',
						    'WoodProducts' => 'WoodProducts',
						    'Other' => 'Other',
					    ),
					    'default_value' => array(
					    ),
					    'allow_null' => 0,
					    'multiple' => 1,
					    'min' => '',
					    'max' => '',
					    'ui' => 1,
					    'ajax' => 1,
					    'return_format' => 'value',
					    'allow_custom' => 0,
					    'placeholder' => 'Exterior Type',
					    'prepend' => '',
					    'append' => '',
					    'acfe_field_group_condition' => 0,
				    ),
				    array(
					    'key' => 'field_627017da88033',
					    'label' => 'Roof Type',
					    'name' => 'roof_type',
					    'type' => 'select',
					    'instructions' => 'Multiples allowed.',
					    'required' => 0,
					    'conditional_logic' => 0,
					    'wrapper' => array(
						    'width' => '',
						    'class' => '',
						    'id' => '',
					    ),
					    'choices' => array(
						    'Asphalt' => 'Asphalt',
						    'BuiltUp' => 'BuiltUp',
						    'Composition' => 'Composition',
						    'Metal' => 'Metal',
						    'ShakeShingle' => 'ShakeShingle',
						    'Slate' => 'Slate',
						    'Tile' => 'Tile',
						    'Other' => 'Other',
					    ),
					    'default_value' => array(
					    ),
					    'allow_null' => 0,
					    'multiple' => 1,
					    'min' => '',
					    'max' => '',
					    'ui' => 1,
					    'ajax' => 1,
					    'return_format' => 'value',
					    'allow_custom' => 0,
					    'placeholder' => 'Roof Type',
					    'prepend' => '',
					    'append' => '',
					    'acfe_field_group_condition' => 0,
				    ),
				    array(
					    'key' => 'field_627016568802d',
					    'label' => 'Cooling System',
					    'name' => 'cooling_system',
					    'type' => 'select',
					    'instructions' => 'Multiples allowed.',
					    'required' => 0,
					    'conditional_logic' => 0,
					    'wrapper' => array(
						    'width' => '',
						    'class' => '',
						    'id' => '',
					    ),
					    'choices' => array(
						    'None' => 'None',
						    'Central' => 'Central',
						    'Evaporative' => 'Evaporative',
						    'Geothermal' => 'Geothermal',
						    'Wall' => 'Wall',
						    'Solar' => 'Solar',
						    'Other' => 'Other',
					    ),
					    'default_value' => array(
					    ),
					    'allow_null' => 0,
					    'multiple' => 1,
					    'min' => '',
					    'max' => '',
					    'ui' => 1,
					    'ajax' => 1,
					    'return_format' => 'value',
					    'allow_custom' => 0,
					    'placeholder' => '',
					    'prepend' => '',
					    'append' => '',
					    'acfe_field_group_condition' => 0,
				    ),
				    array(
					    'key' => 'field_6270179488032',
					    'label' => 'Parking Type',
					    'name' => 'parking_type',
					    'type' => 'select',
					    'instructions' => '',
					    'required' => 0,
					    'conditional_logic' => 0,
					    'wrapper' => array(
						    'width' => '',
						    'class' => '',
						    'id' => '',
					    ),
					    'choices' => array(
						    'Carport' => 'Carport',
						    'GarageAttached' => 'GarageAttached',
						    'GarageDetached' => 'GarageDetached',
						    'OffStreet' => 'OffStreet',
						    'OnStreet' => 'OnStreet',
						    'None' => 'None',
					    ),
					    'default_value' => false,
					    'allow_null' => 0,
					    'multiple' => 0,
					    'max' => '',
					    'ui' => 1,
					    'ajax' => 1,
					    'return_format' => 'value',
					    'allow_custom' => 0,
					    'search_placeholder' => 'Parking Type',
					    'prepend' => '',
					    'append' => '',
					    'acfe_field_group_condition' => 0,
					    'placeholder' => '',
				    ),
				    array(
					    'key' => 'field_62701246a2e77',
					    'label' => 'Promotion',
					    'name' => '',
					    'type' => 'tab',
					    'instructions' => '',
					    'required' => 0,
					    'conditional_logic' => 0,
					    'wrapper' => array(
						    'width' => '',
						    'class' => '',
						    'id' => '',
					    ),
					    'placement' => 'left',
					    'endpoint' => 0,
					    'no_preference' => 0,
					    'acfe_field_group_condition' => 0,
				    ),
				    array(
					    'key' => 'field_6270125aa2e78',
					    'label' => 'Promo Type',
					    'name' => 'promo_type',
					    'type' => 'select',
					    'instructions' => 'Only promotions with a type of consumer will be used.',
					    'required' => 0,
					    'conditional_logic' => 0,
					    'wrapper' => array(
						    'width' => '',
						    'class' => '',
						    'id' => '',
					    ),
					    'choices' => array(
						    'Consumer' => 'Consumer',
						    'Agent' => 'Agent',
					    ),
					    'default_value' => false,
					    'allow_null' => 0,
					    'multiple' => 0,
					    'max' => '',
					    'ui' => 1,
					    'ajax' => 1,
					    'return_format' => 'array',
					    'allow_custom' => 0,
					    'search_placeholder' => 'Promo Type',
					    'prepend' => '',
					    'append' => '',
					    'acfe_field_group_condition' => 0,
					    'placeholder' => '',
				    ),
				    array(
					    'key' => 'field_6270129ca2e79',
					    'label' => 'Promo Headline',
					    'name' => 'promo_headline',
					    'type' => 'text',
					    'instructions' => 'Short description of the promotion.',
					    'required' => 0,
					    'conditional_logic' => array(
						    array(
							    array(
								    'field' => 'field_6270125aa2e78',
								    'operator' => '==',
								    'value' => 'Consumer',
							    ),
						    ),
					    ),
					    'wrapper' => array(
						    'width' => '',
						    'class' => '',
						    'id' => '',
					    ),
					    'default_value' => '',
					    'placeholder' => 'Promo Headline',
					    'prepend' => '',
					    'append' => '',
					    'maxlength' => 100,
					    'acfe_field_group_condition' => 0,
				    ),
				    array(
					    'key' => 'field_627012c6a2e7a',
					    'label' => 'Promo Description',
					    'name' => 'promo_description',
					    'type' => 'text',
					    'instructions' => 'Extended description of the promotion.',
					    'required' => 0,
					    'conditional_logic' => array(
						    array(
							    array(
								    'field' => 'field_6270125aa2e78',
								    'operator' => '==',
								    'value' => 'Consumer',
							    ),
						    ),
					    ),
					    'wrapper' => array(
						    'width' => '',
						    'class' => '',
						    'id' => '',
					    ),
					    'default_value' => '',
					    'placeholder' => 'Promo Description',
					    'prepend' => '',
					    'append' => '',
					    'maxlength' => 250,
					    'acfe_field_group_condition' => 0,
				    ),
				    array(
					    'key' => 'field_627012fda2e7b',
					    'label' => 'Start Date',
					    'name' => 'start_date',
					    'type' => 'date_picker',
					    'instructions' => 'The promotion start date.',
					    'required' => 0,
					    'conditional_logic' => array(
						    array(
							    array(
								    'field' => 'field_6270125aa2e78',
								    'operator' => '==',
								    'value' => 'Consumer',
							    ),
						    ),
					    ),
					    'wrapper' => array(
						    'width' => '',
						    'class' => '',
						    'id' => '',
					    ),
					    'display_format' => 'Y-m-d',
					    'return_format' => 'Y-m-d',
					    'first_day' => 1,
					    'placeholder' => '',
					    'min_date' => '',
					    'max_date' => '',
					    'no_weekends' => 0,
					    'acfe_field_group_condition' => 0,
				    ),
				    array(
					    'key' => 'field_62701328a2e7c',
					    'label' => 'End Date',
					    'name' => 'end_date',
					    'type' => 'date_picker',
					    'instructions' => 'The promotion end date.',
					    'required' => 0,
					    'conditional_logic' => array(
						    array(
							    array(
								    'field' => 'field_6270125aa2e78',
								    'operator' => '==',
								    'value' => 'Consumer',
							    ),
						    ),
					    ),
					    'wrapper' => array(
						    'width' => '',
						    'class' => '',
						    'id' => '',
					    ),
					    'display_format' => 'Y-m-d',
					    'return_format' => 'Y-m-d',
					    'first_day' => 1,
					    'placeholder' => '',
					    'min_date' => '',
					    'max_date' => '',
					    'no_weekends' => 0,
					    'acfe_field_group_condition' => 0,
				    ),
				    array(
					    'key' => 'field_6270140da7281',
					    'label' => 'Amenity',
					    'name' => '',
					    'type' => 'tab',
					    'instructions' => '',
					    'required' => 0,
					    'conditional_logic' => 0,
					    'wrapper' => array(
						    'width' => '',
						    'class' => '',
						    'id' => '',
					    ),
					    'placement' => 'left',
					    'endpoint' => 0,
					    'no_preference' => 0,
					    'acfe_field_group_condition' => 0,
				    ),
				    array(
					    'key' => 'field_62701426a7282',
					    'label' => 'Spec Amenity Type',
					    'name' => 'spec_amenity_type',
					    'type' => 'select',
					    'instructions' => 'Indicate whether a type of amenity exists. This element can be used multiple times, once for each type.',
					    'required' => 0,
					    'conditional_logic' => 0,
					    'wrapper' => array(
						    'width' => '',
						    'class' => '',
						    'id' => '',
					    ),
					    'choices' => array(
						    'BayWindows' => 'Bay Windows',
						    'BreakfastArea' => 'Breakfast Area',
						    'CoveredPatio' => 'Covered Patio',
						    'Fireplaces' => 'Fireplaces',
						    'GreenConstruction' => 'Green Construction',
						    'MudRoom' => 'Mud-Room',
						    'Playroom' => 'Playroom',
						    'VaultedCeilings' => 'Vaulted Ceilings',
						    'WalkInClosets' => 'Walk-In Closets',
					    ),
					    'default_value' => array(
					    ),
					    'allow_null' => 0,
					    'multiple' => 1,
					    'min' => '',
					    'max' => '',
					    'ui' => 1,
					    'ajax' => 1,
					    'return_format' => 'array',
					    'allow_custom' => 0,
					    'placeholder' => 'Spec Amenity Type',
					    'prepend' => '',
					    'append' => '',
					    'acfe_field_group_condition' => 0,
				    ),
				    array(
					    'key' => 'field_627016d28802f',
					    'label' => 'Heating',
					    'name' => '',
					    'type' => 'tab',
					    'instructions' => '',
					    'required' => 0,
					    'conditional_logic' => 0,
					    'wrapper' => array(
						    'width' => '',
						    'class' => '',
						    'id' => '',
					    ),
					    'placement' => 'left',
					    'endpoint' => 0,
					    'no_preference' => 0,
					    'acfe_field_group_condition' => 0,
				    ),
				    array(
					    'key' => 'field_627016e488030',
					    'label' => 'Heating System',
					    'name' => 'heating_system',
					    'type' => 'select',
					    'instructions' => 'Multiples allowed.',
					    'required' => 0,
					    'conditional_logic' => 0,
					    'wrapper' => array(
						    'width' => '',
						    'class' => '',
						    'id' => '',
					    ),
					    'choices' => array(
						    'Baseboard' => 'Baseboard',
						    'ForcedAir' => 'ForcedAir',
						    'HeatPump' => 'HeatPump',
						    'Radiant' => 'Radiant',
						    'Stove' => 'Stove',
						    'Wall' => 'Wall',
						    'Other' => 'Other',
					    ),
					    'default_value' => array(
					    ),
					    'allow_null' => 0,
					    'multiple' => 1,
					    'min' => '',
					    'max' => '',
					    'ui' => 1,
					    'ajax' => 1,
					    'return_format' => 'value',
					    'allow_custom' => 0,
					    'placeholder' => 'Heating System',
					    'prepend' => '',
					    'append' => '',
					    'acfe_field_group_condition' => 0,
				    ),
				    array(
					    'key' => 'field_6270174c88031',
					    'label' => 'Heating Fuel',
					    'name' => 'heating_fuel',
					    'type' => 'select',
					    'instructions' => 'Multiples allowed.',
					    'required' => 0,
					    'conditional_logic' => 0,
					    'wrapper' => array(
						    'width' => '',
						    'class' => '',
						    'id' => '',
					    ),
					    'choices' => array(
						    'None' => 'None',
						    'Coal' => 'Coal',
						    'Electric' => 'Electric',
						    'Gas' => 'Gas',
						    'Oil' => 'Oil',
						    'PropaneButane' => 'PropaneButane',
						    'Solar' => 'Solar',
						    'WoodPellet' => 'WoodPellet',
						    'Other' => 'Other',
					    ),
					    'default_value' => array(
					    ),
					    'allow_null' => 0,
					    'multiple' => 1,
					    'min' => '',
					    'max' => '',
					    'ui' => 1,
					    'ajax' => 1,
					    'return_format' => 'value',
					    'allow_custom' => 0,
					    'placeholder' => 'Heating Fuel',
					    'prepend' => '',
					    'append' => '',
					    'acfe_field_group_condition' => 0,
				    ),
			    ),
			    'location' => array(
				    array(
					    array(
						    'param' => 'post_type',
						    'operator' => '==',
						    'value' => 'homes',
					    ),
				    ),
			    ),
			    'menu_order' => 0,
			    'position' => 'normal',
			    'style' => 'default',
			    'label_placement' => 'top',
			    'instruction_placement' => 'label',
			    'hide_on_screen' => '',
			    'active' => true,
			    'description' => '',
			    'acfe_autosync' => '',
			    'acfe_form' => 0,
			    'acfe_display_title' => '',
			    'acfe_meta' => '',
			    'acfe_note' => '',
		    ));

	    endif;
    }
	