<?php

add_action('init', 'aboutUs');

function aboutUs()
{
	if( function_exists('acf_add_local_field_group') ):

		acf_add_local_field_group(array(
			'key' => 'group_634878e924fa1',
			'title' => 'About Us',
			'fields' => array(
				array(
					'key' => 'field_6348790ebeef9',
					'label' => 'Who We Are Section',
					'name' => '',
					'type' => 'tab',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'placement' => 'left',
					'endpoint' => 0,
					'no_preference' => 0,
					'acfe_field_group_condition' => 0,
				),
				array(
					'key' => 'field_63487993beefa',
					'label' => 'Intro Title',
					'name' => 'wwa_intro_title',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
					'acfe_field_group_condition' => 0,
				),
				array(
					'key' => 'field_634879b4beefb',
					'label' => 'Intro Content',
					'name' => 'wwa_intro_content',
					'type' => 'textarea',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'maxlength' => 700,
					'rows' => 3,
					'new_lines' => 'br',
					'acfe_textarea_code' => 0,
					'acfe_field_group_condition' => 0,
				),
				array(
					'key' => 'field_63487a2abeefc',
					'label' => 'Intro Image',
					'name' => 'wwa_intro_image',
					'type' => 'image',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'uploader' => '',
					'acfe_thumbnail' => 0,
					'return_format' => 'array',
					'preview_size' => 'medium',
					'min_width' => '',
					'min_height' => '',
					'min_size' => '',
					'max_width' => '',
					'max_height' => '',
					'max_size' => '',
					'mime_types' => '',
					'acfe_field_group_condition' => 0,
					'library' => 'all',
				),
				array(
					'key' => 'field_63487a51beefd',
					'label' => 'Section Two',
					'name' => '',
					'type' => 'tab',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'placement' => 'left',
					'endpoint' => 0,
					'no_preference' => 0,
					'acfe_field_group_condition' => 0,
				),
				array(
					'key' => 'field_63487a8abeefe',
					'label' => 'Section Title',
					'name' => 'ast_section_title',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
					'acfe_field_group_condition' => 0,
				),
				array(
					'key' => 'field_63487aa4beeff',
					'label' => 'Section Description',
					'name' => 'ast_section_description',
					'type' => 'textarea',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'maxlength' => 700,
					'rows' => 3,
					'new_lines' => 'br',
					'acfe_textarea_code' => 0,
					'acfe_field_group_condition' => 0,
				),
				array(
					'key' => 'field_63487ad5bef00',
					'label' => 'Section Image',
					'name' => 'sast_ection_image',
					'type' => 'image',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'uploader' => '',
					'acfe_thumbnail' => 0,
					'return_format' => 'array',
					'preview_size' => 'medium',
					'library' => 'all',
					'min_width' => '',
					'min_height' => '',
					'min_size' => '',
					'max_width' => '',
					'max_height' => '',
					'max_size' => '',
					'mime_types' => '',
					'acfe_field_group_condition' => 0,
				),
			),
			'location' => array(
				array(
					array(
						'param' => 'post_template',
						'operator' => '==',
						'value' => 'page-about.blade.php',
					),
				),
			),
			'menu_order' => 0,
			'position' => 'acf_after_title',
			'style' => 'default',
			'label_placement' => 'left',
			'instruction_placement' => 'label',
			'hide_on_screen' => array(
				0 => 'author',
				1 => 'block_editor',
				2 => 'categories',
				3 => 'comments',
				4 => 'the_content',
				5 => 'discussion',
				6 => 'excerpt',
				7 => 'featured_image',
				8 => 'format',
			),
			'active' => true,
			'description' => '',
			'show_in_rest' => 0,
			'acfe_autosync' => '',
			'acfe_form' => 0,
			'acfe_display_title' => '',
			'acfe_meta' => '',
			'acfe_note' => '',
		));

	endif;
}