<?php

add_action('init', 'better_performance');

function better_performance()
{
	if( function_exists('acf_add_local_field_group') ):

		acf_add_local_field_group(array(
			'key' => 'group_6348700e92b9004',
			'title' => 'Better Performance',
			'fields' => array(
				array(
					'key' => 'field_634870145a7b112300',
					'label' => 'Intro Content',
					'name' => '',
					'type' => 'tab',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'placement' => 'left',
					'endpoint' => 0,
					'no_preference' => 0,
					'acfe_field_group_condition' => 0,
				),
				array(
					'key' => 'field_634870295a7b20013',
					'label' => 'Intro Title',
					'name' => 'bf_intro_title',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
					'acfe_field_group_condition' => 0,
				),
				array(
					'key' => 'field_6348705f5a7b302',
					'label' => 'Intro Content',
					'name' => 'bf_intro_content',
					'type' => 'textarea',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'maxlength' => 417,
					'rows' => 3,
					'new_lines' => 'wpautop',
					'acfe_textarea_code' => 0,
					'acfe_field_group_condition' => 0,
				),
                array(
                    'key' => 'field_6499b98ec694389434b',
                    'label' => 'Video',
                    'name' => '',
                    'aria-label' => '',
                    'type' => 'tab',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'acfe_field_group_condition' => 0,
                    'placement' => 'top',
                    'endpoint' => 0,
                    'no_preference' => 0,
                ),
                array(
                    'key' => 'field_6499b9b0c68saddasda0001c',
                    'label' => 'Video URL',
                    'name' => 'bf_video_url',
                    'aria-label' => '',
                    'type' => 'url',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'acfe_field_group_condition' => 0,
                    'default_value' => '',
                    'placeholder' => '',
                ),

				array(
					'key' => 'field_634870b55a7b4340',
					'label' => 'Repeater Section',
					'name' => 'bf_repeater_section',
					'type' => 'repeater',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'acfe_repeater_stylised_button' => 0,
					'collapsed' => '',
					'min' => 0,
					'max' => 4,
					'layout' => 'block',
					'button_label' => '',
					'acfe_field_group_condition' => 0,
					'sub_fields' => array(
                        array(
                            'key' => 'field_64d64c9894161',
                            'label' => 'image',
                            'name' => 'bf_image',
                            'aria-label' => '',
                            'type' => 'image',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                        ),
						array(
							'key' => 'field_634870f15a7b3420012',
							'label' => 'Section Title',
							'name' => 'bf_section_title',
							'type' => 'text',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
							'maxlength' => '',
							'acfe_field_group_condition' => 0,
						),
						array(
							'key' => 'field_634871075a7be342310',
							'label' => 'Section Description',
							'name' => 'bf_section_description',
							'type' => 'textarea',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => '',
							'maxlength' => 641,
							'rows' => 8,
							'new_lines' => 'wpautop',
							'acfe_textarea_code' => 0,
							'acfe_field_group_condition' => 0,
						),
						array(
							'key' => 'field_634871385a7b9801',
							'label' => 'Section Image',
							'name' => 'bf_section_image',
							'type' => 'image',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'uploader' => '',
							'acfe_thumbnail' => 0,
							'return_format' => 'array',
							'preview_size' => 'medium',
							'min_width' => '',
							'min_height' => '',
							'min_size' => '',
							'max_width' => '',
							'max_height' => '',
							'max_size' => '',
							'mime_types' => '',
							'acfe_field_group_condition' => 0,
							'library' => 'all',
						),
					),
				),
			),
			'location' => array(
				array(
					array(
						'param' => 'post_template',
						'operator' => '==',
						'value' => 'page-better-performance.blade.php',
					),
				),
			),
			'menu_order' => 0,
			'position' => 'acf_after_title',
			'style' => 'default',
			'label_placement' => 'left',
			'instruction_placement' => 'label',
			'hide_on_screen' => array(
				0 => 'author',
				1 => 'block_editor',
				2 => 'categories',
				3 => 'comments',
				4 => 'the_content',
				5 => 'discussion',
				6 => 'excerpt',
				7 => 'featured_image',
				8 => 'format',
			),
			'active' => true,
			'description' => '',
			'show_in_rest' => 0,
			'acfe_autosync' => '',
			'acfe_form' => 0,
			'acfe_display_title' => '',
			'acfe_meta' => '',
			'acfe_note' => '',
		));

	endif;
}