<?php

add_action('init', 'contact');

function contact()
{
	if( function_exists('acf_add_local_field_group') ):

		acf_add_local_field_group(array(
			'key' => 'group_635829f5dca2b',
			'title' => 'Contact Page',
			'fields' => array(
				array(
					'key' => 'field_63582a2031ab3',
					'label' => 'Intro Content',
					'name' => '',
					'type' => 'tab',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'placement' => 'left',
					'endpoint' => 0,
					'no_preference' => 0,
					'acfe_field_group_condition' => 0,
				),
				array(
					'key' => 'field_63582a3631ab4',
					'label' => 'Intro Title',
					'name' => 'intro_title',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
					'acfe_field_group_condition' => 0,
				),
				array(
					'key' => 'field_63582a3e31ab5',
					'label' => 'Contact Form Shortcode',
					'name' => 'contact_form_shortcode',
					'type' => 'wysiwyg',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'tabs' => 'visual',
					'toolbar' => 'basic',
					'media_upload' => 0,
					'delay' => 0,
					'acfe_wysiwyg_height' => 200,
					'acfe_wysiwyg_max_height' => '',
					'acfe_wysiwyg_valid_elements' => '',
					'acfe_wysiwyg_custom_style' => '',
					'acfe_wysiwyg_disable_wp_style' => 0,
					'acfe_wysiwyg_autoresize' => 0,
					'acfe_wysiwyg_disable_resize' => 0,
					'acfe_wysiwyg_remove_path' => 0,
					'acfe_wysiwyg_menubar' => 0,
					'acfe_wysiwyg_transparent' => 0,
					'acfe_wysiwyg_merge_toolbar' => 0,
					'acfe_wysiwyg_custom_toolbar' => 0,
					'acfe_field_group_condition' => 0,
				),
				array(
					'key' => 'field_63582af031ab9',
					'label' => 'Model Homes Location',
					'name' => '',
					'type' => 'tab',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'placement' => 'left',
					'endpoint' => 0,
					'no_preference' => 0,
					'acfe_field_group_condition' => 0,
				),
				array(
					'key' => 'field_6362700b1853a',
					'label' => 'Title',
					'name' => 'title_one',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
					'acfe_field_group_condition' => 0,
				),
				array(
					'key' => 'field_63582b0c31aba',
					'label' => 'Address',
					'name' => 'address_one',
					'type' => 'textarea',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'maxlength' => '',
					'rows' => 3,
					'new_lines' => 'br',
					'acfe_textarea_code' => 0,
					'acfe_field_group_condition' => 0,
				),
				array(
					'key' => 'field_63582b1a31abb',
					'label' => 'Phone Number',
					'name' => 'phone_number_one',
					'type' => 'number',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'min' => '',
					'max' => '',
					'step' => '',
					'acfe_field_group_condition' => 0,
				),
				array(
					'key' => 'field_63582aa031ab6',
					'label' => 'Corporate Office',
					'name' => '',
					'type' => 'tab',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'placement' => 'left',
					'endpoint' => 0,
					'no_preference' => 0,
					'acfe_field_group_condition' => 0,
				),
				array(
					'key' => 'field_6362701e1853b',
					'label' => 'Title',
					'name' => 'title_two',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
					'acfe_field_group_condition' => 0,
				),
				array(
					'key' => 'field_63582abf31ab7',
					'label' => 'Address',
					'name' => 'address_two',
					'type' => 'textarea',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'maxlength' => '',
					'rows' => 3,
					'new_lines' => 'br',
					'acfe_textarea_code' => 0,
					'acfe_field_group_condition' => 0,
				),
				array(
					'key' => 'field_63582ad931ab8',
					'label' => 'Phone Number',
					'name' => 'phone_number_two',
					'type' => 'number',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'min' => '',
					'max' => '',
					'step' => '',
					'acfe_field_group_condition' => 0,
				),
				array(
					'key' => 'field_63582b3531abc',
					'label' => 'New Home Consultant',
					'name' => '',
					'type' => 'tab',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'placement' => 'left',
					'endpoint' => 0,
					'no_preference' => 0,
					'acfe_field_group_condition' => 0,
				),
				array(
					'key' => 'field_6362702d1853c',
					'label' => 'Title',
					'name' => 'title_three',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
					'acfe_field_group_condition' => 0,
				),
				array(
					'key' => 'field_63582b4a31abd',
					'label' => 'Address',
					'name' => 'address_three',
					'type' => 'textarea',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'maxlength' => '',
					'rows' => 3,
					'new_lines' => 'br',
					'acfe_textarea_code' => 0,
					'acfe_field_group_condition' => 0,
				),
				array(
					'key' => 'field_63582b5b31abe',
					'label' => 'Phone Number',
					'name' => 'phone_number_three',
					'type' => 'number',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'min' => '',
					'max' => '',
					'step' => '',
					'acfe_field_group_condition' => 0,
				),
			),
			'location' => array(
				array(
					array(
						'param' => 'page_template',
						'operator' => '==',
						'value' => 'page-contact.blade.php',
					),
				),
			),
			'menu_order' => 0,
			'position' => 'acf_after_title',
			'style' => 'default',
			'label_placement' => 'top',
			'instruction_placement' => 'label',
			'hide_on_screen' => array(
				0 => 'author',
				1 => 'block_editor',
				2 => 'categories',
				3 => 'comments',
				4 => 'the_content',
				5 => 'discussion',
				6 => 'excerpt',
				7 => 'featured_image',
				8 => 'format',
			),
			'active' => true,
			'description' => '',
			'show_in_rest' => 1,
			'acfe_autosync' => '',
			'acfe_form' => 0,
			'acfe_display_title' => '',
			'acfe_meta' => '',
			'acfe_note' => '',
		));

	endif;
}