<?php

add_action('init', 'frontpage');

function frontpage()
{
//    if( function_exists('acf_add_local_field_group') ):
//
//        acf_add_local_field_group( array(
//            'key' => 'group_63332081ad0a4',
//            'title' => 'Home Page',
//            'fields' => array(
//                array(
//                    'key' => 'field_633321d130184',
//                    'label' => 'Hero Banner',
//                    'name' => '',
//                    'aria-label' => '',
//                    'type' => 'tab',
//                    'instructions' => '',
//                    'required' => 0,
//                    'conditional_logic' => 0,
//                    'wrapper' => array(
//                        'width' => '',
//                        'class' => '',
//                        'id' => '',
//                    ),
//                    'placement' => 'left',
//                    'endpoint' => 0,
//                    'no_preference' => 0,
//                    'acfe_field_group_condition' => 0,
//                ),
//                array(
//                    'key' => 'field_633321fd30185',
//                    'label' => 'Hero Title',
//                    'name' => 'hero_title',
//                    'aria-label' => '',
//                    'type' => 'text',
//                    'instructions' => '',
//                    'required' => 0,
//                    'conditional_logic' => 0,
//                    'wrapper' => array(
//                        'width' => '',
//                        'class' => '',
//                        'id' => '',
//                    ),
//                    'default_value' => '',
//                    'placeholder' => '',
//                    'prepend' => '',
//                    'append' => '',
//                    'maxlength' => '',
//                    'acfe_field_group_condition' => 0,
//                ),
//                array(
//                    'key' => 'field_6333220c30186',
//                    'label' => 'Hero Sub-title',
//                    'name' => 'hero_sub-title',
//                    'aria-label' => '',
//                    'type' => 'text',
//                    'instructions' => '',
//                    'required' => 0,
//                    'conditional_logic' => 0,
//                    'wrapper' => array(
//                        'width' => '',
//                        'class' => '',
//                        'id' => '',
//                    ),
//                    'default_value' => '',
//                    'placeholder' => '',
//                    'prepend' => '',
//                    'append' => '',
//                    'maxlength' => '',
//                    'acfe_field_group_condition' => 0,
//                ),
//                array(
//                    'key' => 'field_6333222630187',
//                    'label' => 'Hero Button Link',
//                    'name' => 'hero_button_link',
//                    'aria-label' => '',
//                    'type' => 'link',
//                    'instructions' => '',
//                    'required' => 0,
//                    'conditional_logic' => 0,
//                    'wrapper' => array(
//                        'width' => '',
//                        'class' => '',
//                        'id' => '',
//                    ),
//                    'return_format' => 'array',
//                    'acfe_field_group_condition' => 0,
//                ),
//                array(
//                    'key' => 'field_6333224030188',
//                    'label' => 'Hero Banner Image',
//                    'name' => 'hero_banner_image',
//                    'aria-label' => '',
//                    'type' => 'image',
//                    'instructions' => '',
//                    'required' => 0,
//                    'conditional_logic' => 0,
//                    'wrapper' => array(
//                        'width' => '',
//                        'class' => '',
//                        'id' => '',
//                    ),
//                    'uploader' => '',
//                    'acfe_thumbnail' => 0,
//                    'return_format' => 'array',
//                    'preview_size' => 'medium',
//                    'min_width' => '',
//                    'min_height' => '',
//                    'min_size' => '',
//                    'max_width' => '',
//                    'max_height' => '',
//                    'max_size' => '',
//                    'mime_types' => '',
//                    'acfe_field_group_condition' => 0,
//                    'library' => 'all',
//                ),
//                array(
//                    'key' => 'field_633322f7f7ac6',
//                    'label' => 'Better Process Section',
//                    'name' => '',
//                    'aria-label' => '',
//                    'type' => 'tab',
//                    'instructions' => '',
//                    'required' => 0,
//                    'conditional_logic' => 0,
//                    'wrapper' => array(
//                        'width' => '',
//                        'class' => '',
//                        'id' => '',
//                    ),
//                    'acfe_field_group_condition' => 0,
//                    'placement' => 'left',
//                    'endpoint' => 0,
//                    'no_preference' => 0,
//                ),
//                array(
//                    'key' => 'field_6333232ef7ac8',
//                    'label' => 'Title',
//                    'name' => 'wsh_title',
//                    'aria-label' => '',
//                    'type' => 'text',
//                    'instructions' => '',
//                    'required' => 0,
//                    'conditional_logic' => 0,
//                    'wrapper' => array(
//                        'width' => '',
//                        'class' => '',
//                        'id' => '',
//                    ),
//                    'default_value' => '',
//                    'placeholder' => '',
//                    'prepend' => '',
//                    'append' => '',
//                    'maxlength' => '',
//                    'acfe_field_group_condition' => 0,
//                ),
//                array(
//                    'key' => 'field_63332343f7ac9',
//                    'label' => 'Content',
//                    'name' => 'wsh_content',
//                    'aria-label' => '',
//                    'type' => 'textarea',
//                    'instructions' => '',
//                    'required' => 0,
//                    'conditional_logic' => 0,
//                    'wrapper' => array(
//                        'width' => '',
//                        'class' => '',
//                        'id' => '',
//                    ),
//                    'acfe_field_group_condition' => 0,
//                    'default_value' => '',
//                    'acfe_textarea_code' => 0,
//                    'maxlength' => 354,
//                    'rows' => 4,
//                    'placeholder' => '',
//                    'new_lines' => 'wpautop',
//                ),
//                array(
//                    'key' => 'field_63332364f7aca',
//                    'label' => 'Link',
//                    'name' => 'wsh_link',
//                    'aria-label' => '',
//                    'type' => 'link',
//                    'instructions' => '',
//                    'required' => 0,
//                    'conditional_logic' => 0,
//                    'wrapper' => array(
//                        'width' => '',
//                        'class' => '',
//                        'id' => '',
//                    ),
//                    'return_format' => 'array',
//                    'acfe_field_group_condition' => 0,
//                ),
//                array(
//                    'key' => 'field_63332376f7acb',
//                    'label' => 'Featured Image',
//                    'name' => 'wsh_featured_image',
//                    'aria-label' => '',
//                    'type' => 'image',
//                    'instructions' => '',
//                    'required' => 0,
//                    'conditional_logic' => 0,
//                    'wrapper' => array(
//                        'width' => '',
//                        'class' => '',
//                        'id' => '',
//                    ),
//                    'uploader' => '',
//                    'acfe_thumbnail' => 0,
//                    'return_format' => 'array',
//                    'preview_size' => 'medium',
//                    'min_width' => '',
//                    'min_height' => '',
//                    'min_size' => '',
//                    'max_width' => '',
//                    'max_height' => '',
//                    'max_size' => '',
//                    'mime_types' => '',
//                    'acfe_field_group_condition' => 0,
//                    'library' => 'all',
//                ),
//                array(
//                    'key' => 'field_6499a31af4b3d',
//                    'label' => 'Better Performance',
//                    'name' => '',
//                    'aria-label' => '',
//                    'type' => 'tab',
//                    'instructions' => '',
//                    'required' => 0,
//                    'conditional_logic' => 0,
//                    'wrapper' => array(
//                        'width' => '',
//                        'class' => '',
//                        'id' => '',
//                    ),
//                    'acfe_field_group_condition' => 0,
//                    'placement' => 'left',
//                    'endpoint' => 0,
//                    'no_preference' => 0,
//                ),
//                array(
//                    'key' => 'field_6499a332f4b3e',
//                    'label' => 'Title',
//                    'name' => 'bp2_title',
//                    'aria-label' => '',
//                    'type' => 'text',
//                    'instructions' => '',
//                    'required' => 0,
//                    'conditional_logic' => 0,
//                    'wrapper' => array(
//                        'width' => '',
//                        'class' => '',
//                        'id' => '',
//                    ),
//                    'acfe_field_group_condition' => 0,
//                    'default_value' => '',
//                    'maxlength' => '',
//                    'placeholder' => '',
//                    'prepend' => '',
//                    'append' => '',
//                ),
//                array(
//                    'key' => 'field_6499a366f4b3f',
//                    'label' => 'Content',
//                    'name' => 'bp2__content_copy',
//                    'aria-label' => '',
//                    'type' => 'textarea',
//                    'instructions' => '',
//                    'required' => 0,
//                    'conditional_logic' => 0,
//                    'wrapper' => array(
//                        'width' => '',
//                        'class' => '',
//                        'id' => '',
//                    ),
//                    'acfe_field_group_condition' => 0,
//                    'default_value' => '',
//                    'acfe_textarea_code' => 0,
//                    'maxlength' => 354,
//                    'rows' => 4,
//                    'placeholder' => '',
//                    'new_lines' => 'wpautop',
//                ),
//                array(
//                    'key' => 'field_6499a382f4b40',
//                    'label' => 'Link',
//                    'name' => 'bp2_link',
//                    'aria-label' => '',
//                    'type' => 'link',
//                    'instructions' => '',
//                    'required' => 0,
//                    'conditional_logic' => 0,
//                    'wrapper' => array(
//                        'width' => '',
//                        'class' => '',
//                        'id' => '',
//                    ),
//                    'acfe_field_group_condition' => 0,
//                    'return_format' => 'array',
//                ),
//                array(
//                    'key' => 'field_6499a39df4b41',
//                    'label' => 'Featured Image',
//                    'name' => 'bp2_featured_image_copy',
//                    'aria-label' => '',
//                    'type' => 'image',
//                    'instructions' => '',
//                    'required' => 0,
//                    'conditional_logic' => 0,
//                    'wrapper' => array(
//                        'width' => '',
//                        'class' => '',
//                        'id' => '',
//                    ),
//                    'acfe_field_group_condition' => 0,
//                    'uploader' => '',
//                    'acfe_thumbnail' => 0,
//                    'return_format' => 'array',
//                    'min_width' => '',
//                    'min_height' => '',
//                    'min_size' => '',
//                    'max_width' => '',
//                    'max_height' => '',
//                    'max_size' => '',
//                    'mime_types' => '',
//                    'preview_size' => 'medium',
//                    'library' => 'all',
//                ),
//                array(
//                    'key' => 'field_6499a42de4939',
//                    'label' => 'Better Future',
//                    'name' => '',
//                    'aria-label' => '',
//                    'type' => 'tab',
//                    'instructions' => '',
//                    'required' => 0,
//                    'conditional_logic' => 0,
//                    'wrapper' => array(
//                        'width' => '',
//                        'class' => '',
//                        'id' => '',
//                    ),
//                    'acfe_field_group_condition' => 0,
//                    'placement' => 'left',
//                    'endpoint' => 0,
//                    'no_preference' => 0,
//                ),
//                array(
//                    'key' => 'field_6499a444e493a',
//                    'label' => 'Title',
//                    'name' => 'bf_title',
//                    'aria-label' => '',
//                    'type' => 'text',
//                    'instructions' => '',
//                    'required' => 0,
//                    'conditional_logic' => 0,
//                    'wrapper' => array(
//                        'width' => '',
//                        'class' => '',
//                        'id' => '',
//                    ),
//                    'acfe_field_group_condition' => 0,
//                    'default_value' => '',
//                    'maxlength' => '',
//                    'placeholder' => '',
//                    'prepend' => '',
//                    'append' => '',
//                ),
//                array(
//                    'key' => 'field_6499a45ee493b',
//                    'label' => 'Content',
//                    'name' => 'bf__content',
//                    'aria-label' => '',
//                    'type' => 'textarea',
//                    'instructions' => '',
//                    'required' => 0,
//                    'conditional_logic' => 0,
//                    'wrapper' => array(
//                        'width' => '',
//                        'class' => '',
//                        'id' => '',
//                    ),
//                    'acfe_field_group_condition' => 0,
//                    'default_value' => '',
//                    'acfe_textarea_code' => 0,
//                    'maxlength' => 354,
//                    'rows' => 4,
//                    'placeholder' => '',
//                    'new_lines' => 'wpautop',
//                ),
//                array(
//                    'key' => 'field_6499a465e493c',
//                    'label' => 'Link',
//                    'name' => 'bf_link_copy',
//                    'aria-label' => '',
//                    'type' => 'link',
//                    'instructions' => '',
//                    'required' => 0,
//                    'conditional_logic' => 0,
//                    'wrapper' => array(
//                        'width' => '',
//                        'class' => '',
//                        'id' => '',
//                    ),
//                    'acfe_field_group_condition' => 0,
//                    'return_format' => 'array',
//                ),
//                array(
//                    'key' => 'field_6499a46ce493d',
//                    'label' => 'Featured Image',
//                    'name' => 'bf_featured_image',
//                    'aria-label' => '',
//                    'type' => 'image',
//                    'instructions' => '',
//                    'required' => 0,
//                    'conditional_logic' => 0,
//                    'wrapper' => array(
//                        'width' => '',
//                        'class' => '',
//                        'id' => '',
//                    ),
//                    'acfe_field_group_condition' => 0,
//                    'uploader' => '',
//                    'acfe_thumbnail' => 0,
//                    'return_format' => 'array',
//                    'min_width' => '',
//                    'min_height' => '',
//                    'min_size' => '',
//                    'max_width' => '',
//                    'max_height' => '',
//                    'max_size' => '',
//                    'mime_types' => '',
//                    'preview_size' => 'medium',
//                    'library' => 'all',
//                ),
//                array(
//                    'key' => 'field_633324546454d731c02',
//                    'label' => 'Find Your Home',
//                    'name' => '',
//                    'type' => 'tab',
//                    'instructions' => '',
//                    'required' => 0,
//                    'conditional_logic' => 0,
//                    'wrapper' => array(
//                        'width' => '',
//                        'class' => '',
//                        'id' => '',
//                    ),
//                    'placement' => 'top',
//                    'endpoint' => 0,
//                    'no_preference' => 0,
//                    'acfe_field_group_condition' => 0,
//                ),
//                array(
//                    'key' => 'field_63332443434fdef31c03',
//                    'label' => 'Where Do You Want To Live Section',
//                    'name' => 'where_do_you_want_to_live_section',
//                    'type' => 'repeater',
//                    'instructions' => '',
//                    'required' => 0,
//                    'conditional_logic' => 0,
//                    'wrapper' => array(
//                        'width' => '',
//                        'class' => '',
//                        'id' => '',
//                    ),
//                    'acfe_repeater_stylised_button' => 0,
//                    'collapsed' => '',
//                    'min' => 0,
//                    'max' => 3,
//                    'layout' => 'block',
//                    'button_label' => 'Add New',
//                    'acfe_field_group_condition' => 0,
//                    'sub_fields' => array(
//                        array(
//                            'key' => 'field_633334546250b31c04',
//                            'label' => 'Featured Image',
//                            'name' => 'featured_image',
//                            'type' => 'image',
//                            'instructions' => '',
//                            'required' => 0,
//                            'conditional_logic' => 0,
//                            'wrapper' => array(
//                                'width' => '',
//                                'class' => '',
//                                'id' => '',
//                            ),
//                            'uploader' => '',
//                            'acfe_thumbnail' => 0,
//                            'return_format' => 'array',
//                            'preview_size' => 'medium',
//                            'min_width' => '',
//                            'min_height' => '',
//                            'min_size' => '',
//                            'max_width' => '',
//                            'max_height' => '',
//                            'max_size' => '',
//                            'mime_types' => '',
//                            'acfe_field_group_condition' => 0,
//                            'library' => 'all',
//                        ),
//                        array(
//                            'key' => 'field_633323453445451831c05',
//                            'label' => 'Link',
//                            'name' => 'link',
//                            'type' => 'link',
//                            'instructions' => '',
//                            'required' => 0,
//                            'conditional_logic' => 0,
//                            'wrapper' => array(
//                                'width' => '',
//                                'class' => '',
//                                'id' => '',
//                            ),
//                            'return_format' => 'array',
//                            'acfe_field_group_condition' => 0,
//                        ),
//                    ),
//                ),
//                array(
//                    'key' => 'field_63332875927ed',
//                    'label' => 'Discovery South Jordan Section',
//                    'name' => '',
//                    'aria-label' => '',
//                    'type' => 'tab',
//                    'instructions' => '',
//                    'required' => 0,
//                    'conditional_logic' => 0,
//                    'wrapper' => array(
//                        'width' => '',
//                        'class' => '',
//                        'id' => '',
//                    ),
//                    'placement' => 'top',
//                    'endpoint' => 0,
//                    'no_preference' => 0,
//                    'acfe_field_group_condition' => 0,
//                ),
//                array(
//                    'key' => 'field_63332890927ee',
//                    'label' => 'Sub-title',
//                    'name' => 'dsj_sub-title',
//                    'aria-label' => '',
//                    'type' => 'text',
//                    'instructions' => '',
//                    'required' => 0,
//                    'conditional_logic' => 0,
//                    'wrapper' => array(
//                        'width' => '',
//                        'class' => '',
//                        'id' => '',
//                    ),
//                    'default_value' => '',
//                    'placeholder' => '',
//                    'prepend' => '',
//                    'append' => '',
//                    'maxlength' => '',
//                    'acfe_field_group_condition' => 0,
//                ),
//                array(
//                    'key' => 'field_6333289e927ef',
//                    'label' => 'Title',
//                    'name' => 'dsj_title',
//                    'aria-label' => '',
//                    'type' => 'text',
//                    'instructions' => '',
//                    'required' => 0,
//                    'conditional_logic' => 0,
//                    'wrapper' => array(
//                        'width' => '',
//                        'class' => '',
//                        'id' => '',
//                    ),
//                    'default_value' => '',
//                    'placeholder' => '',
//                    'prepend' => '',
//                    'append' => '',
//                    'maxlength' => '',
//                    'acfe_field_group_condition' => 0,
//                ),
//                array(
//                    'key' => 'field_633328bc927f0',
//                    'label' => 'Content',
//                    'name' => 'dsj_content',
//                    'aria-label' => '',
//                    'type' => 'textarea',
//                    'instructions' => '',
//                    'required' => 0,
//                    'conditional_logic' => 0,
//                    'wrapper' => array(
//                        'width' => '',
//                        'class' => '',
//                        'id' => '',
//                    ),
//                    'default_value' => '',
//                    'placeholder' => '',
//                    'maxlength' => 252,
//                    'rows' => 3,
//                    'new_lines' => 'wpautop',
//                    'acfe_textarea_code' => 0,
//                    'acfe_field_group_condition' => 0,
//                ),
//                array(
//                    'key' => 'field_633328e2927f1',
//                    'label' => 'Link',
//                    'name' => 'dsj_link',
//                    'aria-label' => '',
//                    'type' => 'link',
//                    'instructions' => '',
//                    'required' => 0,
//                    'conditional_logic' => 0,
//                    'wrapper' => array(
//                        'width' => '',
//                        'class' => '',
//                        'id' => '',
//                    ),
//                    'return_format' => 'array',
//                    'acfe_field_group_condition' => 0,
//                ),
//                array(
//                    'key' => 'field_63332a1f927f2',
//                    'label' => 'Featured Background Image',
//                    'name' => 'featured_background_image',
//                    'aria-label' => '',
//                    'type' => 'image',
//                    'instructions' => '',
//                    'required' => 0,
//                    'conditional_logic' => 0,
//                    'wrapper' => array(
//                        'width' => '',
//                        'class' => '',
//                        'id' => '',
//                    ),
//                    'uploader' => '',
//                    'acfe_thumbnail' => 0,
//                    'return_format' => 'array',
//                    'preview_size' => 'medium',
//                    'min_width' => '',
//                    'min_height' => '',
//                    'min_size' => '',
//                    'max_width' => '',
//                    'max_height' => '',
//                    'max_size' => '',
//                    'mime_types' => '',
//                    'acfe_field_group_condition' => 0,
//                    'library' => 'all',
//                ),
//            ),
//            'location' => array(
//                array(
//                    array(
//                        'param' => 'post_template',
//                        'operator' => '==',
//                        'value' => 'front-page.blade.php',
//                    ),
//                ),
//            ),
//            'menu_order' => 0,
//            'position' => 'acf_after_title',
//            'style' => 'default',
//            'label_placement' => 'top',
//            'instruction_placement' => 'field',
//            'hide_on_screen' => array(
//                0 => 'the_content',
//                1 => 'excerpt',
//                2 => 'discussion',
//                3 => 'comments',
//                4 => 'author',
//                5 => 'featured_image',
//                6 => 'categories',
//            ),
//            'active' => true,
//            'description' => '',
//            'show_in_rest' => 1,
//        ) );
//
//
//
//    endif;

    if( function_exists('acf_add_local_field_group') ):

        acf_add_local_field_group( array(
            'key' => 'group_63332081ad0a4',
            'title' => 'Home Page',
            'fields' => array(
                array(
                    'key' => 'field_633321d130184',
                    'label' => 'Hero Banner',
                    'name' => '',
                    'aria-label' => '',
                    'type' => 'tab',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'placement' => 'left',
                    'endpoint' => 0,
                    'no_preference' => 0,
                    'acfe_field_group_condition' => 0,
                ),
                array(
                    'key' => 'field_633321fd30185',
                    'label' => 'Hero Title',
                    'name' => 'hero_title',
                    'aria-label' => '',
                    'type' => 'text',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'default_value' => '',
                    'placeholder' => '',
                    'prepend' => '',
                    'append' => '',
                    'maxlength' => '',
                    'acfe_field_group_condition' => 0,
                ),
                array(
                    'key' => 'field_6333220c30186',
                    'label' => 'Hero Sub-title',
                    'name' => 'hero_sub-title',
                    'aria-label' => '',
                    'type' => 'text',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'default_value' => '',
                    'placeholder' => '',
                    'prepend' => '',
                    'append' => '',
                    'maxlength' => '',
                    'acfe_field_group_condition' => 0,
                ),
                array(
                    'key' => 'field_6333222630187',
                    'label' => 'Hero Button Link',
                    'name' => 'hero_button_link',
                    'aria-label' => '',
                    'type' => 'link',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'return_format' => 'array',
                    'acfe_field_group_condition' => 0,
                ),
                array(
                    'key' => 'field_6333224030188',
                    'label' => 'Hero Banner Image',
                    'name' => 'hero_banner_image',
                    'aria-label' => '',
                    'type' => 'image',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'uploader' => '',
                    'acfe_thumbnail' => 0,
                    'return_format' => 'array',
                    'preview_size' => 'medium',
                    'min_width' => '',
                    'min_height' => '',
                    'min_size' => '',
                    'max_width' => '',
                    'max_height' => '',
                    'max_size' => '',
                    'mime_types' => '',
                    'acfe_field_group_condition' => 0,
                    'library' => 'all',
                ),
                array(
                    'key' => 'field_633322f7f7ac6',
                    'label' => 'Better Process Section',
                    'name' => '',
                    'aria-label' => '',
                    'type' => 'tab',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'acfe_field_group_condition' => 0,
                    'placement' => 'left',
                    'endpoint' => 0,
                    'no_preference' => 0,
                ),
                array(
                    'key' => 'field_6333232ef7ac8',
                    'label' => 'Title',
                    'name' => 'wsh_title',
                    'aria-label' => '',
                    'type' => 'text',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'default_value' => '',
                    'placeholder' => '',
                    'prepend' => '',
                    'append' => '',
                    'maxlength' => '',
                    'acfe_field_group_condition' => 0,
                ),
                array(
                    'key' => 'field_63332343f7ac9',
                    'label' => 'Content',
                    'name' => 'wsh_content',
                    'aria-label' => '',
                    'type' => 'textarea',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'acfe_field_group_condition' => 0,
                    'default_value' => '',
                    'acfe_textarea_code' => 0,
                    'maxlength' => 354,
                    'rows' => 4,
                    'placeholder' => '',
                    'new_lines' => 'wpautop',
                ),
                array(
                    'key' => 'field_63332364f7aca',
                    'label' => 'Link',
                    'name' => 'wsh_link',
                    'aria-label' => '',
                    'type' => 'link',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'return_format' => 'array',
                    'acfe_field_group_condition' => 0,
                ),
                array(
                    'key' => 'field_63332376f7acb',
                    'label' => 'Featured Image',
                    'name' => 'wsh_featured_image',
                    'aria-label' => '',
                    'type' => 'image',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'uploader' => '',
                    'acfe_thumbnail' => 0,
                    'return_format' => 'array',
                    'preview_size' => 'medium',
                    'min_width' => '',
                    'min_height' => '',
                    'min_size' => '',
                    'max_width' => '',
                    'max_height' => '',
                    'max_size' => '',
                    'mime_types' => '',
                    'acfe_field_group_condition' => 0,
                    'library' => 'all',
                ),
                array(
                    'key' => 'field_6499a31af4b3d',
                    'label' => 'Better Performance',
                    'name' => '',
                    'aria-label' => '',
                    'type' => 'tab',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'acfe_field_group_condition' => 0,
                    'placement' => 'left',
                    'endpoint' => 0,
                    'no_preference' => 0,
                ),
                array(
                    'key' => 'field_6499a332f4b3e',
                    'label' => 'Title',
                    'name' => 'bp2_title',
                    'aria-label' => '',
                    'type' => 'text',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'acfe_field_group_condition' => 0,
                    'default_value' => '',
                    'maxlength' => '',
                    'placeholder' => '',
                    'prepend' => '',
                    'append' => '',
                ),
                array(
                    'key' => 'field_6499a366f4b3f',
                    'label' => 'Content',
                    'name' => 'bp2__content_copy',
                    'aria-label' => '',
                    'type' => 'textarea',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'acfe_field_group_condition' => 0,
                    'default_value' => '',
                    'acfe_textarea_code' => 0,
                    'maxlength' => 354,
                    'rows' => 4,
                    'placeholder' => '',
                    'new_lines' => 'wpautop',
                ),
                array(
                    'key' => 'field_6499a382f4b40',
                    'label' => 'Link',
                    'name' => 'bp2_link',
                    'aria-label' => '',
                    'type' => 'link',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'acfe_field_group_condition' => 0,
                    'return_format' => 'array',
                ),
                array(
                    'key' => 'field_6499a39df4b41',
                    'label' => 'Featured Image',
                    'name' => 'bp2_featured_image_copy',
                    'aria-label' => '',
                    'type' => 'image',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'acfe_field_group_condition' => 0,
                    'uploader' => '',
                    'acfe_thumbnail' => 0,
                    'return_format' => 'array',
                    'min_width' => '',
                    'min_height' => '',
                    'min_size' => '',
                    'max_width' => '',
                    'max_height' => '',
                    'max_size' => '',
                    'mime_types' => '',
                    'preview_size' => 'medium',
                    'library' => 'all',
                ),
                array(
                    'key' => 'field_6499a42de4939',
                    'label' => 'Better Future',
                    'name' => '',
                    'aria-label' => '',
                    'type' => 'tab',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'acfe_field_group_condition' => 0,
                    'placement' => 'left',
                    'endpoint' => 0,
                    'no_preference' => 0,
                ),
                array(
                    'key' => 'field_6499a444e493a',
                    'label' => 'Title',
                    'name' => 'bf_title',
                    'aria-label' => '',
                    'type' => 'text',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'acfe_field_group_condition' => 0,
                    'default_value' => '',
                    'maxlength' => '',
                    'placeholder' => '',
                    'prepend' => '',
                    'append' => '',
                ),
                array(
                    'key' => 'field_6499a45ee493b',
                    'label' => 'Content',
                    'name' => 'bf__content',
                    'aria-label' => '',
                    'type' => 'textarea',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'acfe_field_group_condition' => 0,
                    'default_value' => '',
                    'acfe_textarea_code' => 0,
                    'maxlength' => 354,
                    'rows' => 4,
                    'placeholder' => '',
                    'new_lines' => 'wpautop',
                ),
                array(
                    'key' => 'field_6499a465e493c',
                    'label' => 'Link',
                    'name' => 'bf_link_copy',
                    'aria-label' => '',
                    'type' => 'link',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'acfe_field_group_condition' => 0,
                    'return_format' => 'array',
                ),
                array(
                    'key' => 'field_6499a46ce493d',
                    'label' => 'Featured Image',
                    'name' => 'bf_featured_image',
                    'aria-label' => '',
                    'type' => 'image',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'acfe_field_group_condition' => 0,
                    'uploader' => '',
                    'acfe_thumbnail' => 0,
                    'return_format' => 'array',
                    'min_width' => '',
                    'min_height' => '',
                    'min_size' => '',
                    'max_width' => '',
                    'max_height' => '',
                    'max_size' => '',
                    'mime_types' => '',
                    'preview_size' => 'medium',
                    'library' => 'all',
                ),
                array(
                    'key' => 'field_633324d731c02',
                    'label' => 'Find Your Home',
                    'name' => '',
                    'aria-label' => '',
                    'type' => 'tab',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'placement' => 'top',
                    'endpoint' => 0,
                    'no_preference' => 0,
                    'acfe_field_group_condition' => 0,
                ),
                array(
                    'key' => 'field_633324ef31c03',
                    'label' => 'Where Do You Want To Live Section',
                    'name' => 'where_do_you_want_to_live_section',
                    'aria-label' => '',
                    'type' => 'repeater',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'acfe_field_group_condition' => 0,
                    'acfe_repeater_stylised_button' => 0,
                    'layout' => 'block',
                    'pagination' => 0,
                    'min' => 3,
                    'max' => 3,
                    'collapsed' => '',
                    'button_label' => 'Add Row',
                    'rows_per_page' => 20,
                    'sub_fields' => array(
                        array(
                            'key' => 'field_6333250b31c04',
                            'label' => 'Featured Image',
                            'name' => 'featured_image',
                            'aria-label' => '',
                            'type' => 'image',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'uploader' => '',
                            'acfe_thumbnail' => 0,
                            'return_format' => 'array',
                            'preview_size' => 'medium',
                            'min_width' => '',
                            'min_height' => '',
                            'min_size' => '',
                            'max_width' => '',
                            'max_height' => '',
                            'max_size' => '',
                            'mime_types' => '',
                            'acfe_field_group_condition' => 0,
                            'library' => 'all',
                            'parent_repeater' => 'field_633324ef31c03',
                        ),
                        array(
                            'key' => 'field_64b8255ff9c4f',
                            'label' => 'Link',
                            'name' => 'link',
                            'aria-label' => '',
                            'type' => 'link',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'acfe_field_group_condition' => 0,
                            'return_format' => 'array',
                            'parent_repeater' => 'field_633324ef31c03',
                        ),
                    ),
                ),
                array(
                    'key' => 'field_63332875927ed',
                    'label' => 'Discovery South Jordan Section',
                    'name' => '',
                    'aria-label' => '',
                    'type' => 'tab',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'placement' => 'top',
                    'endpoint' => 0,
                    'no_preference' => 0,
                    'acfe_field_group_condition' => 0,
                ),
                array(
                    'key' => 'field_63332890927ee',
                    'label' => 'Sub-title',
                    'name' => 'dsj_sub-title',
                    'aria-label' => '',
                    'type' => 'text',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'default_value' => '',
                    'placeholder' => '',
                    'prepend' => '',
                    'append' => '',
                    'maxlength' => '',
                    'acfe_field_group_condition' => 0,
                ),
                array(
                    'key' => 'field_6333289e927ef',
                    'label' => 'Title',
                    'name' => 'dsj_title',
                    'aria-label' => '',
                    'type' => 'text',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'default_value' => '',
                    'placeholder' => '',
                    'prepend' => '',
                    'append' => '',
                    'maxlength' => '',
                    'acfe_field_group_condition' => 0,
                ),
                array(
                    'key' => 'field_633328bc927f0',
                    'label' => 'Content',
                    'name' => 'dsj_content',
                    'aria-label' => '',
                    'type' => 'textarea',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'default_value' => '',
                    'placeholder' => '',
                    'maxlength' => 252,
                    'rows' => 3,
                    'new_lines' => 'wpautop',
                    'acfe_textarea_code' => 0,
                    'acfe_field_group_condition' => 0,
                ),
                array(
                    'key' => 'field_633328e2927f1',
                    'label' => 'Link',
                    'name' => 'dsj_link',
                    'aria-label' => '',
                    'type' => 'link',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'return_format' => 'array',
                    'acfe_field_group_condition' => 0,
                ),
                array(
                    'key' => 'field_63332a1f927f2',
                    'label' => 'Featured Background Image',
                    'name' => 'featured_background_image',
                    'aria-label' => '',
                    'type' => 'image',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'uploader' => '',
                    'acfe_thumbnail' => 0,
                    'return_format' => 'array',
                    'preview_size' => 'medium',
                    'min_width' => '',
                    'min_height' => '',
                    'min_size' => '',
                    'max_width' => '',
                    'max_height' => '',
                    'max_size' => '',
                    'mime_types' => '',
                    'acfe_field_group_condition' => 0,
                    'library' => 'all',
                ),
            ),
            'location' => array(
                array(
                    array(
                        'param' => 'post_template',
                        'operator' => '==',
                        'value' => 'front-page.blade.php',
                    ),
                ),
            ),
            'menu_order' => 0,
            'position' => 'acf_after_title',
            'style' => 'default',
            'label_placement' => 'top',
            'instruction_placement' => 'field',
            'hide_on_screen' => array(
                0 => 'author',
                1 => 'categories',
                2 => 'comments',
                3 => 'the_content',
                4 => 'discussion',
                5 => 'excerpt',
                6 => 'featured_image',
            ),
            'active' => true,
            'description' => '',
            'show_in_rest' => 1,
            'acfe_autosync' => '',
            'acfe_form' => 0,
            'acfe_display_title' => '',
            'acfe_meta' => '',
            'acfe_note' => '',
        ) );

    endif;
}