<?php

add_action('init', 'newnused');

function newnused()
{
	if( function_exists('acf_add_local_field_group') ):

		acf_add_local_field_group(array(
			'key' => 'group_63486add49f00',
			'title' => 'New vs. Used',
			'fields' => array(
				array(
					'key' => 'field_63486b6cfd204',
					'label' => 'Intro Content',
					'name' => '',
					'type' => 'tab',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'placement' => 'left',
					'endpoint' => 0,
					'no_preference' => 0,
					'acfe_field_group_condition' => 0,
				),
				array(
					'key' => 'field_63486b8ffd205',
					'label' => 'Intro Title',
					'name' => 'nu_intro_title',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
					'acfe_field_group_condition' => 0,
				),
				array(
					'key' => 'field_63486bacfd206',
					'label' => 'Intro Content',
					'name' => 'nu_intro_content',
					'type' => 'textarea',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'maxlength' => 268,
					'rows' => 3,
					'new_lines' => 'wpautop',
					'acfe_textarea_code' => 0,
					'acfe_field_group_condition' => 0,
				),
				array(
					'key' => 'field_63486be9fd207',
					'label' => 'Before and After Image',
					'name' => 'nu_before_and_after_image',
					'type' => 'group',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'layout' => 'block',
					'acfe_seamless_style' => 0,
					'acfe_group_modal' => 0,
					'acfe_field_group_condition' => 0,
					'sub_fields' => array(
						array(
							'key' => 'field_63486c42fd208',
							'label' => 'Before Image',
							'name' => 'nu_before_image',
							'type' => 'image',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'uploader' => '',
							'acfe_thumbnail' => 0,
							'return_format' => 'array',
							'preview_size' => 'medium',
							'min_width' => '',
							'min_height' => '',
							'min_size' => '',
							'max_width' => '',
							'max_height' => '',
							'max_size' => '',
							'mime_types' => '',
							'acfe_field_group_condition' => 0,
							'library' => 'all',
						),
						array(
							'key' => 'field_63486c62fd209',
							'label' => 'After Image',
							'name' => 'nu_after_image',
							'type' => 'image',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'uploader' => '',
							'acfe_thumbnail' => 0,
							'return_format' => 'array',
							'preview_size' => 'medium',
							'min_width' => '',
							'min_height' => '',
							'min_size' => '',
							'max_width' => '',
							'max_height' => '',
							'max_size' => '',
							'mime_types' => '',
							'acfe_field_group_condition' => 0,
							'library' => 'all',
						),
					),
				),
				array(
					'key' => 'field_63486d26fd20a',
					'label' => 'Repeater Section',
					'name' => 'repeater_section',
					'type' => 'repeater',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'acfe_repeater_stylised_button' => 0,
					'collapsed' => '',
					'min' => 1,
					'max' => 4,
					'layout' => 'block',
					'button_label' => '',
					'acfe_field_group_condition' => 0,
					'sub_fields' => array(
						array(
							'key' => 'field_63486d59fd20b',
							'label' => 'Section Title',
							'name' => 'section_title',
							'type' => 'text',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
							'maxlength' => '',
							'acfe_field_group_condition' => 0,
						),
						array(
							'key' => 'field_63486ea6fd20c',
							'label' => 'Section Description',
							'name' => 'section_description',
							'type' => 'text',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
							'maxlength' => '',
							'acfe_field_group_condition' => 0,
						),
						array(
							'key' => 'field_63486eb1fd20d',
							'label' => 'Section Link',
							'name' => 'section_link',
							'type' => 'link',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'return_format' => 'array',
							'acfe_field_group_condition' => 0,
						),
						array(
							'key' => 'field_634871b85eb31',
							'label' => 'Section Image',
							'name' => 'nu_section_image',
							'type' => 'image',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'uploader' => '',
							'acfe_thumbnail' => 0,
							'return_format' => 'array',
							'preview_size' => 'medium',
							'min_width' => '',
							'min_height' => '',
							'min_size' => '',
							'max_width' => '',
							'max_height' => '',
							'max_size' => '',
							'mime_types' => '',
							'acfe_field_group_condition' => 0,
							'library' => 'all',
						),
					),
				),
			),
			'location' => array(
				array(
					array(
						'param' => 'post_template',
						'operator' => '==',
						'value' => 'page-new-used.blade.php',
					),
				),
			),
			'menu_order' => 0,
			'position' => 'acf_after_title',
			'style' => 'default',
			'label_placement' => 'left',
			'instruction_placement' => 'label',
			'hide_on_screen' => array(
				0 => 'author',
				1 => 'block_editor',
				2 => 'categories',
				3 => 'comments',
				4 => 'the_content',
				5 => 'discussion',
				6 => 'excerpt',
				7 => 'featured_image',
			),
			'active' => true,
			'description' => '',
			'show_in_rest' => 0,
			'acfe_autosync' => '',
			'acfe_form' => 0,
			'acfe_display_title' => '',
			'acfe_meta' => '',
			'acfe_note' => '',
		));

	endif;
}