name: PHP Lint

on:
  pull_request:
    branches:
      - staging

jobs:
  php-lint:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.3" # or your desired PHP version
          extensions: mbstring, xml

      - name: Install Composer Dependencies
        run: composer install --prefer-dist --no-interaction

      - name: Run PHP Lint
        run: find . -name '*.php' -exec php -l {} \;
