name: Testing

on:
  pull_request:
    branches: [main]
jobs:
  phpunit:
    name: Run PHPUnit Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Composer Dependencies
        run: composer install
      - name: Run PHPUnit Tests
        run: ./vendor/bin/phpunit

  eslint:
    name: Run ESLint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Yarn Dependencies
        run: yarn install
      - name: Run ESLint
        run: yarn eslint --ext .js,.jsx,.ts,.tsx wp-content/themes/simmsdev

  phpcs:
    name: Run PHPCS
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Composer Dependencies
        run: composer install
      - name: Run PHPCS
        run: ./vendor/bin/phpcs --standard=phpcs.xml.dist wp-content/themes/simmsdev

  tailwindcss:
    name: Build TailwindCSS
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Yarn Dependencies
        run: yarn install
      - name: Build TailwindCSS
        run: yarn build
